### ISSUE TITLE
Installation using Ubuntu 14.04 a little different

### ISSUE THREAD

**Issue by JakePrice86** [blockchain/service-my-wallet-v3#10]
Just a quick note, I couldn't install using the npm code you provided, but by using this snippet instead:

    npm install -g git+https://github.com/blockchain/service-my-wallet-v3.git

**Comment by kristovatlas** [comment]
Hey @JakePrice86, thanks for letting us know.

**Comment by jtormey** [comment]
Thanks @JakePrice86, the README has been changed to show the correct protocol (ea69599)
