### ISSUE TITLE
Cannot install blockchain-wallet-service

### ISSUE THREAD

**Issue by minha361** [blockchain/service-my-wallet-v3#103]
My npm version is 2.15.1 Node version is v4.4.3 CentOS release 6.7 (Final) When I run

npm install -g blockchain-wallet-service
Console show error:

gyp ERR! build error gyp ERR! stack Error: make failed with exit code: 2 gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23) gyp ERR! stack at emitTwo (events.js:87:13) gyp ERR! stack at ChildProcess.emit (events.js:172:7) gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12) gyp ERR! System Linux 2.6.32-573.el6.x86_64 gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" gyp ERR! cwd /usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/ws/node_modules/utf-8-validate gyp ERR! node -v v4.4.3 gyp ERR! node-gyp -v v3.3.1 gyp ERR! not ok
Then I try to run service "blockchain-wallet-service start --port 3000" and try to connect to the service

curl -X POST 'http://localhost:3000/api/v2/create?api_code=myCode&password=aPassword'
In the service console has message

Error: RNG.run [ReferenceError: XMLHttpRequest is not defined] 1462457502389 - error: Error generating the entropyReferenceError: XMLHttpRequest is not defined
Please tell me how to fix this Issue The blockchain-wallet-service require node >= 0.12.0 and npm >= 2.12.0, < 3.0.0 Here is url that I use https://github.com/blockchain/service-my-wallet-v3 Thanks very much!

node.js

**Comment by minha361** [comment]
my host using java 1.8

**Comment by jtormey** [comment]
Hi, what version of the service are you using? It might be that you just need to upgrade.

**Comment by minha361** [comment]
I setup service for new computer. when I check version it is 0.21

**Comment by jtormey** [comment]
The node-gyp errors don't prevent installation, it's safe to ignore those since they are generated by an optional dependency. The error you're seeing when trying to create a wallet is a separate issue (unrelated to the installation) and was fixed in the latest patch release.
