### ISSUE TITLE
ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by minha361** [blockchain/service-my-wallet-v3#104]
When i connect to my service to create wallet. Have exception
curl -X POST 'http://localhost:3000/api/v2/create?api_code=MY_API_CODE&password=aPassword'

Here is exception from serve

blockchain-wallet-service start 3000
1462543239750 - info: blockchain.info wallet service v0.21.1 running on http://127.0.0.1:3000
Error: RNG.run
[ReferenceError: XMLHttpRequest is not defined]
1462543250721 - error: Error generating the entropyReferenceError: XMLHttpRequest is not defined

Here is my server information 

[root@xm11110 ~]# node -v
v0.12.13
[root@xm11110 ~]# npm -v
2.15.0
[root@xm11110 ~]# blockchain-wallet-service -V
0.21.1

**Comment by jtormey** [comment]
It looks like there's an issue with wallet creation in the latest version. I'll release a fix shortly, thanks for letting us know about this!

**Comment by jtormey** [comment]
Fixed in v0.21.2
