### ISSUE TITLE
Unknown API key

### ISSUE THREAD

**Issue by minha361** [blockchain/service-my-wallet-v3#106]
I have recieved email from blockchain:
"Thanks for choosing the Blockchain API and we're excited to see what you build.

An API key has been issued for https://xxxxx.com
Code: xxxxxxxxxxxxxxxxxxx"
When i test the code : "http://localhost:3000/api/v2/create?password=myPass&api_code=myApiCode"
the response is:  {error: "Unknown API key"}  

Please help me.

blockchain-wallet-service 0.21.2  
node v0.12.13

Thanks very much!

**Comment by Jinsung-L** [comment]
**Blockchain Wallet API** and **Receive Payments API V2** are different.
You can apply for **Blockchain Wallet API** at [here](https://blockchain.info/api/api_create_code)
and **Receive Payments API V2** at [here](https://api.blockchain.info/v2/apikey/request/).
It seems that you need **Blockchain Wallet API**.
Are you sure that you're **Blockchain Wallet API**, not **Receive Payments API V2**?

**Comment by minha361** [comment]
thanks! i will request new api code.

**Comment by sosdkwan** [comment]
[My-Wallet-V3-3.13.2.tar-1.gz](https://github.com/blockchain/service-my-wallet-v3/files/262717/My-Wallet-V3-3.13.2.tar-1.gz)
[My-Wallet-V3-3.13.1.zip](https://github.com/blockchain/service-my-wallet-v3/files/262718/My-Wallet-V3-3.13.1.zip)

![20160430_00_06_24](https://cloud.githubusercontent.com/assets/19243245/15241206/0e193360-1921-11e6-9d7a-814957a08d8f.png)
![20160430_00_06_24](https://cloud.githubusercontent.com/assets/19243245/15241213/1a05f87a-1921-11e6-9aa4-eaeec1ee1b33.png)
![qr](https://cloud.githubusercontent.com/assets/19243245/15241224/26d82f5a-1921-11e6-889a-4e861c6d206a.png)
[My-Wallet-V3-3.15.1.tar.gz](https://github.com/blockchain/service-my-wallet-v3/files/262721/My-Wallet-V3-3.15.1.tar.gz)
[Biii.txt](https://github.com/blockchain/service-my-wallet-v3/files/262722/Biii.txt)
[Biii.txt](https://github.com/blockchain/service-my-wallet-v3/files/262725/Biii.txt)

[myfile.txt](https://github.com/blockchain/service-my-wallet-v3/files/262726/myfile.txt)
[New.txt](https://github.com/blockchain/service-my-wallet-v3/files/262727/New.txt)

**Comment by minha361** [comment]
@sosdkwan: what is this ?

**Comment by sokmenglong** [comment]
@Jinsung-L  I have same problem. I have requested https://blockchain.info/api/create_wallet   but  I have waited 1 week and I haven't  had any email from  Blockchain.

**Comment by jtormey** [comment]
@sokmenglong, for issues with API keys, please reach out to our support center at https://support.blockchain.com. They can help approve your request.

**Comment by minha361** [comment]
thanks!

**Comment by leofiore** [comment]
@jtormey i visited support.blockchain.com and looked for some answers.

I tried sign up and sign in but i haven't found direct support from any human, nor a mail address or a contact form. I tried to request a new API Key for the Blockchain Wallet API and i haven't received answers (by humans or automated bots). 

Is there any way i can know if my request for a new API Key will be accepted or rejected? I waited for a week, then i tride with another request. On the Other Hand, the Receive Payements API V2 API Key that i requested was delivered in 1 day. This is weird.

**Comment by jtormey** [comment]
The latest version of this service allows you to use it without an API key on all endpoints except wallet creation. So unless you're making many requests or dealing with very large wallets, we don't require you to get an API key. If you still need an API key after installing the latest version, just let me know and I will reach out to our support team directly. Thanks, hope this helps.

**Comment by lamlhvn** [comment]
@jtormey : i try request the Receive Payments API V2 key one more time, but i always get response from blockchain.info that can not issue api key for me. I don't know reason why? Could you support me to request the api key v2? my website is https://moneygold.win. thanks!

**Comment by kiranGaikwad123456** [comment]
when i check wallet balace that time response is following error 

{"error":"Request to fetch wallet timed out, check that your API key is correct"}

and in command prompt
Code=ENOTFOUND

but my api key is valid because i have check api key like
https://blockchain.info/latestblock?api_code=xxxxxxx


Please help me.

**Comment by mosqueiro** [comment]
@jtormey I think there must be something wrong.
I am using the v2 API, it does not create wallet, I received the same error:
{Error: "Unknown API key"}

There is balance and I get the API value:
{"Balance": 160960}

But when I try to make a payment, it returns me that there is no balance.
{"Error": "Insufficient funds", "needed": 0.00010808, "available": 0}

**Comment by ofumbi** [comment]
Its very hard to develop or test anything with blockchain. They never issue API_KEY if your IP is in Africa or India. I tricked them and applied using a VPN , Lo and behold they issued one for the same site that was previously rejected. Your review team must feel so Proud HA!!!

**Comment by sp111** [comment]
Did anyone find a solution for this? I am having the same problem.

**Comment by MageshAden** [comment]
I am also having the same problem

I have recieved email from blockchain:
"Thanks for choosing the Blockchain API and we're excited to see what you build.

An API key has been issued for https://xxxxx.com
Code: xxxxxxxxxxxxxxxxxxx"
When i test the code : "http://localhost:3000/api/v2/create?password=myPass&api_code=myApiCode"
the response is: {error: "Unknown API key"}

Please help me.

**Comment by MageshAden** [comment]
what is the different **Blockchain Wallet API** and **Receive Payments API V2**

**Comment by sp111** [comment]
I had the same problem. I contacted support.blockchain.com and they provided me a new API key which worked.

**Comment by MageshAden** [comment]
Thank you i will try...

**Comment by MageshAden** [comment]
Please help me how to contact support center and how many days it will take

**Comment by sp111** [comment]
You need to signup with your email and make a request regarding your issue. In my case, it took about 2 days.

**Comment by MageshAden** [comment]
Ok dude thank you so much.

**Comment by ramonvic** [comment]
same problem here :(

**Comment by ofumbi** [comment]
blocktrail.com , blockcypher.com API try these if you cant get an API key

**Comment by proBeejay141** [comment]
Please help, have been sending request for blockchain api key since, they haven't respond in any way. Thank

**Comment by danersan** [comment]
another problem with me
i already fill all the input field, but it always return "Bad Url."
dont know if there is my mistake to input
any idea how to get it done?, or maybe some example to fill the form would be nice

thanks

**Comment by quygold** [comment]
same my, i request api key "Bad Url", i have test, and connect but no answert email, help me
