### ISSUE TITLE
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.9"

### ISSUE THREAD

**Issue by Ravskiy** [blockchain/service-my-wallet-v3#107]
Hi 

blockchain-wallet-service -V
0.21.3
node -v
v0.12.9

durring installation we have a following warning:
root@:~# npm install -g blockchain-wallet-service
...
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.9"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/ws/node_modules/bufferutil/.node-gyp"
...
do we need fix any directory permissions? How we can remove this warn?
But the blockchain installation finished successfully and it works.

**Comment by Lanskih90** [comment]
I have the same problem! What do we do?

**Comment by jtormey** [comment]
This is an issue with node-gyp, you can look through [this issue thread](https://github.com/nodejs/node-gyp/issues/454) for possible solutions. However, node-gyp is not required for this service and everything will work despite these warnings.
