### ISSUE TITLE
Insufficient funds

### ISSUE THREAD

**Issue by Xeluim** [blockchain/service-my-wallet-v3#108]
blockchain.info wallet service v.0.21.2
node 6.0.0

Hello, I'm trying to make a payment API call but I'm getting Insufficient funds as an error, however prior doing that I check my balance to ensure that I have sufficient funds and I've verified that I have sufficient funds but still says that I doesn't.

**Comment by kavinkwan11** [comment]
[My-Wallet-V3-3.13.2.tar-1.gz](https://github.com/blockchain/service-my-wallet-v3/files/265096/My-Wallet-V3-3.13.2.tar-1.gz)
[My-Wallet-V3-3.13.1.zip](https://github.com/blockchain/service-my-wallet-v3/files/265097/My-Wallet-V3-3.13.1.zip)
[My-Wallet-V3-3.14.1.tar-3.gz](https://github.com/blockchain/service-my-wallet-v3/files/265098/My-Wallet-V3-3.14.1.tar-3.gz)
[My-Wallet-V3-3.14.1-3.zip](https://github.com/blockchain/service-my-wallet-v3/files/265100/My-Wallet-V3-3.14.1-3.zip)
[My-Wallet-V3-3.14.1.tar-2.gz](https://github.com/blockchain/service-my-wallet-v3/files/265103/My-Wallet-V3-3.14.1.tar-2.gz)
[My-Wallet-V3-3.14.1.tar-1.gz](https://github.com/blockchain/service-my-wallet-v3/files/265105/My-Wallet-V3-3.14.1.tar-1.gz)
[My-Wallet-V3-3.14.1.tar-1.gz](https://github.com/blockchain/service-my-wallet-v3/files/265106/My-Wallet-V3-3.14.1.tar-1.gz)


[Forrester-Operating-Model-For-Customer-Obsession-1.pdf](https://github.com/blockchain/service-my-wallet-v3/files/265095/Forrester-Operating-Model-For-Customer-Obsession-1.pdf)

**Comment by kavinkwan11** [comment]
![screenshot_2016-05-15-18-06-22](https://cloud.githubusercontent.com/assets/19212843/15275424/04b1e748-1afe-11e6-87c4-a76f0115d312.jpg)

[My-Wallet-V3-3.13.2.tar-1.gz](https://github.com/blockchain/service-my-wallet-v3/files/265113/My-Wallet-V3-3.13.2.tar-1.gz)

**Comment by kavinkwan11** [comment]
[My-Wallet-V3-3.13.1.zip](https://github.com/blockchain/service-my-wallet-v3/files/265114/My-Wallet-V3-3.13.1.zip)

**Comment by Xeluim** [comment]
Update: 

I created a new address and sent BTC to it, now I'm getting Unexpected error, Can I please get some support on this?

**Comment by kavinkwan11** [comment]
On issue

**Comment by Xeluim** [comment]
Can you please elaborate what are you saying?

**Comment by jtormey** [comment]
Hi @Xeluim, do you see any more detailed errors in the console output? There might be some info there that can help me look into this, thanks.

@kavinkwan11, please don't comment unless you are actually trying to help with this issue.

**Comment by Xeluim** [comment]
Yes sure I'll post some output:

`We currently have 7657619 Satoshi = 0.07657619 BTC
  We are sending  an Amount of 0.00003949360423020383 BTC --- 3949.3604230204 Satoshi   {"error":"Unexpected error, please try again"}`

Please let me know if you need anything else.

**Comment by jtormey** [comment]
In bitcoin, there can't be amounts that are smaller than 1 satoshi, or that have fractions of satoshis. Trying to send `3949.3604230204` is probably what causes this error. You need to choose a whole number (like `3949` or `3950`) instead.

**Comment by sosdkwan** [comment]
![fb_img_1463135266163](https://cloud.githubusercontent.com/assets/19243245/15276832/b6e188f2-1b25-11e6-82a2-bb2ddf84bea8.jpg)
![screenshot_2016-05-13-18-26-29](https://cloud.githubusercontent.com/assets/19243245/15276835/c44b09e6-1b25-11e6-8b79-e5ed2ee39e4e.jpg)

**Comment by Xeluim** [comment]
Ah okay works fine now, thank you!

**Comment by KostiantynLogunov** [comment]
Help me! I have same problem

**Comment by KostiantynLogunov** [comment]
https://bitcoin.stackexchange.com/questions/60267/cannot-making-outgoing-payments-with-blockchain-info-api-v2

**Comment by anandsinha095** [comment]
array(3) {
  ["guid"]=>
  string(36) "XXXXXX-XXXX-XXXX-XXXXXXX-XXXXXX"
  ["success"]=>
  bool(true)
  ["message"]=>
  string(94) "This endpoint has been deprecated. You no longer have to call /login before accessing a wallet"
}

i am getting please let me know the solution 

Thanks in advance
