### ISSUE TITLE
Error: Cannot find module '../node_modules/blockchain-wallet-client-prebuilt/src/helpers' 

### ISSUE THREAD

**Issue by mrmayfield** [blockchain/service-my-wallet-v3#119]
I want to run this module locally, like:

`./node_modules/.bin/wallet-web-service start` but I get the above error

Obviously the paths are not happy. Anything I can do to fix this and run the module locally as opposed to with a global installation?

**Comment by jtormey** [comment]
Hey, thanks for pointing this out. I just released a new version (0.21.4) that gets rid of the unneeded relative paths. A local installation should work now.

**Comment by mrmayfield** [comment]
Cool, thanks. Just a heads up, http://www.justintormey.net is down as well

**Comment by mrmayfield** [comment]
PS: Can you push that version to npm?

**Comment by jtormey** [comment]
Sure, new version is on npm now.

Thanks for the heads up! I changed my site domain and forgot to update it here
