### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Lanskih90** [blockchain/service-my-wallet-v3#12]
**I'm using this command:**
> $ npm install -g https://github.com/blockchain/service-my-wallet-v3.git

**Error:**
> npm http GET https://github.com/blockchain/service-my-wallet-v3.git
> npm http 200 https://github.com/blockchain/service-my-wallet-v3.git
> npm ERR! not a package /home/user/tmp/npm-8114-XR3gqie4/1451382256747-0.5445718949194998/tmp.tgz
> npm ERR! Error: ENOENT, open '/home/user/tmp/npm-8114-XR3gqie4/1451382256747-0.5445718949194998/package/package.json'
> npm ERR! If you need help, you may report this log at:
> npm ERR!     <http://github.com/isaacs/npm/issues>
> npm ERR! or email it to:
> npm ERR!     <npm-@googlegroups.com>

> npm ERR! System Linux 3.13.0-57-generic
> npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "https://github.com/blockchain/service-my-wallet-v3.git"
> npm ERR! cwd /home/user
> npm ERR! node -v v0.10.25
> npm ERR! npm -v 1.3.10
> npm ERR! path /home/user/tmp/npm-8114-XR3gqie4/1451382256747-0.5445718949194998/package/package.json
> npm ERR! code ENOENT
> npm ERR! errno 34
> npm ERR! 
> npm ERR! Additional logging details can be found in:
> npm ERR!     /home/user/npm-debug.log
> npm ERR! not ok code 0

**What the problem?**
**Thanks**

**Comment by JakePrice86** [comment]
Have you tried this? https://github.com/blockchain/service-my-wallet-v3/issues/10

**Comment by Lanskih90** [comment]
the same error

**Comment by Lanskih90** [comment]
I updated npm version from 1.3 to 2.14.
Now display new error:
> npm ERR! tar.unpack untar error /home/bit-apple/.npm/service-my-wallet-v3/0.9.1/package.tgz

**Comment by Lanskih90** [comment]
Fix error:
> npm cache clean
> sudo npm install -g https://github.com/blockchain/service-my-wallet-v3.git

**Comment by KMHouk** [comment]
@Lanskih90 When you say 'Fix error' -- does this mean that you are not having an issue with this anymore?

**Comment by Lanskih90** [comment]
I installed your module, but now I have an error: I can't run your module, here is a link to the error: https://github.com/blockchain/service-my-wallet-v3/issues/13

**Comment by KMHouk** [comment]
Alright. For organizational purposes, since this specific issue is fixed (installing), I'll close this one and we can move over and start working on https://github.com/blockchain/service-my-wallet-v3/issues/13 (running)

**Comment by Lanskih90** [comment]
ok, go to 13

**Comment by Ravskiy** [comment]
I'have error during installation:

ubuntu 14.04 with latest updates.

root@b:/# npm -v
3.6.0
root@b:/# node -v
v0.12.9
root@b:/# npm install -g blockchain-wallet-service
/usr/bin/blockchain-wallet-service -> /usr/lib/node_modules/blockchain-wallet-service/bin/cli.js
/usr/lib
└─┬ blockchain-wallet-service@0.14.0 
  ├─┬ body-parser@1.14.2
  │ └── type-is@1.6.11 
  └─┬ request-promise@1.0.2
    ├── UNMET PEER DEPENDENCY continuation-local-storage@~3
    └─┬ request@2.69.0
      ├─┬ har-validator@2.0.6
      │ └─┬ pinkie-promise@2.0.0
      │   └── pinkie@2.0.3 
      └── oauth-sign@0.8.1 

npm WARN cls-bluebird@1.0.1 requires a peer of continuation-local-storage@~3 but none was installed.
root@b:/#

Can you advice, how to fix the issue?
