### ISSUE TITLE
Why my IP is banned. How to fix 

### ISSUE THREAD

**Issue by minha361** [blockchain/service-my-wallet-v3#122]
Here is my problem when i run my blockchain-wallet-service
Please tell me how to fix it, someone tell me: "To prevent getting banned again, you may want to apply for a free API key here ..." but I'm using API key in my server and now my server IP is banned. Please help me :( 

1465382416860 - info: blockchain.info wallet service v0.21.4 running on http://127.0.0.1:3000 1465382423317 - error:
Please enable cookies.
Error 1006 Ray ID: 2afbb9b137e9126d • 2016-06-08 10:40:23 UTC

Access denied

What happened?

The owner of this website (blockchain.info) has banned your IP address (36.37.215.148).

CloudFlare Ray ID: 2afbb9b137e9126d • Your IP: 36.37.215.148 • Performance & security by CloudFlare

**Comment by jtormey** [comment]
Your IP may have been banned if you were making a lot of requests. Please contact our [support team](https://support.blockchain.com), they can unban your IP for you. If it happens again, you should ask them to raise your API keys request limit.

**Comment by Chidinmambaneto** [comment]
I tried to check in my nftsea airdrop to know the numbers of people I've referred but found out my nftsea IP address got banned. How can I get unban.
Error 1007
Ray ID: 6a57c4b34e8d06fd •
2021-10-28 22:58:21 UTC
Access denied
What happened?
The owner of this website (nftsea.net) has banned your IP address (129.205.113.12).

Cloudflare Ray ID: 6a57c4b34e8d06fd
Your IP: 129.205.113.12
Performance & security by Cloudflare

**Comment by goldenlyon7** [comment]
I tried to check the numbers of referrals I have on nftsea but got this error message below

Error 1007
Ray ID: 6a5e9610cd6f7196 •
2021-10-29 18:49:51 UTC
Access denied
What happened?
The owner of this website (nftsea.net) has banned your IP address (129.205.113.1

**Comment by MAKRAMSH** [comment]
Your IP 111.119.187.21 has been banned 
my ip is banned  
I  can't reach my client area. please help me
