### ISSUE TITLE
MakePayment HD without "from", error: Insufficient funds

### ISSUE THREAD

**Issue by dlimkin** [blockchain/service-my-wallet-v3#123]
Hello, 
MakePayment (for HD Wallet) without "from" parameter, reseponse:

> 1466443503586 - error: Insufficient funds. Value Needed 0.01001BTC. Available amount 0BTC

If from == index or xpub, everything is fine.

 *Service v0.21.4, Node v4.4.5*

**Comment by jtormey** [comment]
At the moment you need to explicitly specify an account index or xpub, otherwise the service will just attempt to spend from your non-hd addresses. If none of those addresses have funds, then it will send that error.
