### ISSUE TITLE
Error signing and pushing transaction

### ISSUE THREAD

**Issue by anver** [blockchain/service-my-wallet-v3#128]
Service v0.21.4, Node v6.2.2

Here is my setup

**Step 1 :**
Generating address using receive payments api v2 and display it to the user, I'm using a seperate table to store all the newly generated addresses in order to fix the address gap issue. The unused addresses in this table will be displayed for other users after a certain amount of time so that the address can be used and that fixes the address gap issue.

**Step 2**
User then sends coins to this address. Callback url is set when generating the address using the receive v2 api, so the callback is fired when the payment comes into that new address

**Step 3**
There are multiple checks to make sure that the payment made is valid etc then after all the checks are complete the user gets their product or memberships.

**Step 4**
After a sale happens affiliate details are added to a separate table, so a cron job will send payments to the affiliates in that table for every 10 minutes or so. This affiliate payment is made from the same wallet which received the payment using the wallet api.

Params used when sending the payments are below and send_coins function will set the correct wallet api code, password and url etc ... inside it

**First Method :** 
$data['from'] = 'addresswhichreceivedpayment';
$data['to'] = 'addressoftheaffiliate';
$data['amount'] = amount_in_satoshi
$data['fee'] = .0001 * 100000000;
send_coins( $data );

**response : Error signing and pushing transaction**

**Second Method :**
$data['from'] = 'xpubkeyusedtogeneratetheaddress';
$data['to'] = 'addressoftheaffiliate';
$data['amount'] = amount_in_satoshi
$data['fee'] = .0001 * 100000000;
send_coins( $data ); 

**response : Error building transaction**

**Third Method :**
$data['from'] = 'generatedaddressindex'; in this case it was 1
$data['to'] = 'addressoftheaffiliate';
$data['amount'] = amount_in_satoshi
$data['fee'] = .0001 * 100000000;
send_coins( $data ); 

**response : Error building transaction**

**Fourth Method :**
$data['to'] = 'addressoftheaffiliate';
$data['amount'] = amount_in_satoshi
$data['fee'] = .0001 * 100000000;
send_coins( $data ); 

**Note From address was removed**

****response** : **{"error: insufficeint funds","needed: .003583","available: 0"}** **

and sometime the error is {"error":"Unexpected error, please try again"}

I can see the address which received the payment under addresses -> used addresses in my wallet and the wallet is displaying the right amount.

I'm struck here, it sends out payments without issue when I use another wallet which has funds on it's main address and I'm not using any "from" params there when using that wallet. I need to send funds from this received address. How can I do that ? Please help.

Thanks.

**Comment by kavinkwan11** [comment]
😂😂😂😂😂😂😂😂
2016/8/9 00:56 於 "anver" <notifications@github.com> 寫道：

**Comment by jtormey** [comment]
The second method listed is the correct way to do this, everything there seems fine so I'm not sure why that's not working. I'll look into it and get back to you. In the meantime, try logging into our web interface and sending manually from there.

**Comment by kavinkwan11** [comment]
依加我欠能咗你呀！
2016/8/9 21:25 於 "Justin Tormey" <notifications@github.com> 寫道：

**Comment by kavinkwan11** [comment]
你老母臭閪
2016/8/9 21:27 於 "Kavin Kwan11" <kavinkwan11@gmail.com> 寫道：

**Comment by kavinkwan11** [comment]
從我的 Samsung Galaxy 智能手機發送。

**Comment by kavinkwan11** [comment]
2016/8/9 21:29 於 "Kavin Kwan11" <kavinkwan11@gmail.com> 寫道：

**Comment by jtormey** [comment]
@kavinkwan11 please don't comment unless you have something constructive to add to the conversation.

**Comment by RIDHA12** [comment]
Service v0.21.4, Node v6.2.2

Here is my setup

Step 1 :
Generating address using receive payments api v2 and display it to the user, I'm using a seperate table to store all the newly generated addresses in order to fix the address gap issue. The unused addresses in this table will be displayed for other users after a certain amount of time so that the address can be used and that fixes the address gap issue.

Step 2
User then sends coins to this address. Callback url is set when generating the address using the receive v2 api, so the callback is fired when the payment comes into that new address

Step 3
There are multiple checks to make sure that the payment made is valid etc then after all the checks are complete the user gets their product or memberships.

Step 4
After a sale happens affiliate details are added to a separate table, so a cron job will send payments to the affiliates in that table for every 10 minutes or so. This affiliate payment is made from the same wallet which received the payment using the wallet api.

Params used when sending the payments are below and send_coins function will set the correct wallet api code, password and url etc ... inside it

First Method : 
$data['from'] = 'addresswhichreceivedpayment';
$data['to'] = 'addressoftheaffiliate';
$data['amount'] = amount_in_satoshi
$data['fee'] = .0001 * 100000000;
send_coins( $data );

response : Error signing and pushing transaction

Second Method :
$data['from'] = 'xpubkeyusedtogeneratetheaddress';
$data['to'] = 'addressoftheaffiliate';
$data['amount'] = amount_in_satoshi
$data['fee'] = .0001 * 100000000;
send_coins( $data );

response : Error building transaction

Third Method :
$data['from'] = 'generatedaddressindex'; in this case it was 1
$data['to'] = 'addressoftheaffiliate';
$data['amount'] = amount_in_satoshi
$data['fee'] = .0001 * 100000000;
send_coins( $data );

response : Error building transaction

Fourth Method :
$data['to'] = 'addressoftheaffiliate';
$data['amount'] = amount_in_satoshi
$data['fee'] = .0001 * 100000000;
send_coins( $data );

Note From address was removed

***response* : {"error: insufficeint funds","needed: .003583","available: 0"} **

and sometime the error is {"error":"Unexpected error, please try again"}

I can see the address which received the payment under addresses -> used addresses in my wallet and the wallet is displaying the right amount.

I'm struck here, it sends out payments without issue when I use another wallet which has funds on it's main address and I'm not using any "from" params there when using that wallet. I need to send funds from this received address. How can I do that ? Please help.

Thanks.

**Comment by anver** [comment]
Some crazy people are spamming this post, really sad to see this happening. Irresponsible douchebags.

**Comment by jtormey** [comment]
Yeah, not great. I'll see what I can do about blocking them.

**Comment by RIDHA12** [comment]
<?php
/**
 * Plugin Name: Coinbase
 * Plugin URI: https://github.com/coinbase/coinbase-wordpress
 * Description: Add Coinbase payment buttons to your WordPress site.
 * Version: 1.0
 * Author: Coinbase Inc.
 * Author URI: https://coinbase.com
 * License: GPLv2 or later
 */
/* 
Copyright (C) 2014 Coinbase Inc.
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
define('COINBASE_PATH', plugin_dir_path( __FILE__ ));
define('COINBASE_URL', plugins_url( '', __FILE__ ));
require_once(plugin_dir_path( __FILE__ ) . 'coinbase-php/lib/Coinbase.php');
require_once(plugin_dir_path( __FILE__ ) . 'widget.php');
class WP_Coinbase {
  private $plugin_path;
  private $plugin_url;
  private $l10n;
  private $wpsf;
  function __construct() {  
    $this->plugin_path = plugin_dir_path( __FILE__ );
    $this->plugin_url = plugin_dir_url( __FILE__ );
    $this->l10n = 'wp-settings-framework';
    add_action( 'admin_menu', array(&$this, 'admin_menu'), 99 );
    add_action( 'admin_init', array(&$this, 'admin_init'), 99 );
    add_action('admin_enqueue_scripts', array(&$this, 'admin_styles'), 1);
    add_action('admin_enqueue_scripts', array(&$this, 'widget_scripts'));
    // Include and create a new WordPressSettingsFramework
    require_once( $this->plugin_path .'wp-settings-framework.php' );
    $this->wpsf = new WordPressSettingsFramework( $this->plugin_path .'settings/coinbase.php' );
    add_shortcode('coinbase_button', array(&$this, 'shortcode'));
  }
  function admin_menu() {
    add_submenu_page( 'options-general.php', __( 'Coinbase', $this->l10n ), __( 'Coinbase', $this->l10n ), 'update_core', 'coinbase', array(&$this, 'settings_page') );
  }
  function admin_init() {
    register_setting ( 'coinbase', 'coinbase-tokens' );
  }
  function settings_page() {
    $api_key = wpsf_get_setting( 'coinbase', 'general', 'api_key' );
    $api_secret = wpsf_get_setting( 'coinbase', 'general', 'api_secret' );
    ?>
      <div class="wrap">
        <div id="icon-options-general" class="icon32"></div>
        <h2>Coinbase</h2>

    <?php
        $this->wpsf->settings();
    ?>
      </div>
    <?php
  }
  function shortcode( $atts, $content = null ) {
    $defaults = array(
          'name'               => 'test',
          'price_string'       => '1.23',
          'price_currency_iso' => 'USD',
          'custom'             => 'Order123',
          'description'        => 'Sample description',
          'type'               => 'buy_now',
          'style'              => 'buy_now_large',
          'text'               => 'Pay with Bitcoin',
          'choose_price'       => false,
          'variable_price'     => false,
          'price1'             => '0.0',
          'price2'             => '0.0',
          'price3'             => '0.0',
          'price4'             => '0.0',
          'price5'             => '0.0',
    );
    $args = shortcode_atts($defaults, $atts, 'coinbase_button');
    // Clear default price suggestions
    for ($i = 1; $i <= 5; $i++) {
      if ($args["price$i"] == '0.0') {
        unset($args["price$i"]);
      }
    }
    $transient_name = 'cb_ecc_' . md5(serialize($args));
    $cached = get_transient($transient_name);
    if($cached !== false) {
      return $cached;
    }
    $api_key = wpsf_get_setting( 'coinbase', 'general', 'api_key' );
    $api_secret = wpsf_get_setting( 'coinbase', 'general', 'api_secret' );
    if( $api_key && $api_secret ) {
      try {
        $coinbase = Coinbase::withApiKey($api_key, $api_secret);
        $button = $coinbase->createButtonWithOptions($args)->embedHtml;
      } catch (Exception $e) {
        $msg = $e->getMessage();
        error_log($msg);
        return "There was an error connecting to Coinbase: $msg. Please check your internet connection and API credentials.";
      }
      set_transient($transient_name, $button);
      return $button;
    } else {
      return "The Coinbase plugin has not been properly set up - please visit the Coinbase settings page in your administrator console.";
    }
  }
  public function admin_styles() {
    wp_enqueue_style( 'coinbase-admin-styles', COINBASE_URL .'/css/coinbase-admin.css', array(), '1', 'all' );
  }
  public function widget_scripts( $hook ) {
    if( 'widgets.php' != $hook )
      return;
    wp_enqueue_script( 'coinbase-widget-scripts', COINBASE_URL .'/js/coinbase-widget.js', array('jquery'), '', true );
  }
}
new WP_Coinbase();
?>

**Comment by RIDHA12** [comment]
<?php
/**
* Plugin Name: Coinbase
* Plugin URI: https://github.com/coinbase/coinbase-wordpress
* Description: Add Coinbase payment buttons to your WordPress site.
* Version: 1.0
* Author: Coinbase Inc.
* Author URI: https://coinbase.com
* License: GPLv2 or later
*/
/*
Copyright (C) 2014 Coinbase Inc.
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
USA.
*/
define('COINBASE_PATH', plugin_dir_path( __FILE__ ));
define('COINBASE_URL', plugins_url( '', __FILE__ ));
require_once(plugin_dir_path( __FILE__ ) . 'coinbase-php/lib/Coinbase.php');
require_once(plugin_dir_path( __FILE__ ) . 'widget.php');
class WP_Coinbase {
private $plugin_path;
private $plugin_url;
private $l10n;
private $wpsf;
function __construct() {
$this->plugin_path = plugin_dir_path( __FILE__ );
$this->plugin_url = plugin_dir_url( __FILE__ );
$this->l10n = 'wp-settings-framework';
add_action( 'admin_menu', array(&$this, 'admin_menu'), 99 );
add_action( 'admin_init', array(&$this, 'admin_init'), 99 );
add_action('admin_enqueue_scripts', array(&$this, 'admin_styles'), 1);
add_action('admin_enqueue_scripts', array(&$this, 'widget_scripts'));
// Include and create a new WordPressSettingsFramework
require_once( $this->plugin_path .'wp-settings-framework.php' );
$this->wpsf = new WordPressSettingsFramework( $this->plugin_path .'
settings/coinbase.php' );
add_shortcode('coinbase_button', array(&$this, 'shortcode'));
}
function admin_menu() {
add_submenu_page( 'options-general.php', __( 'Coinbase', $this->l10n ), __(
'Coinbase', $this->l10n ), 'update_core', 'coinbase', array(&$this, '
settings_page') );
}
function admin_init() {
register_setting ( 'coinbase', 'coinbase-tokens' );
}
function settings_page() {
$api_key = wpsf_get_setting( 'coinbase', 'general', 'api_key' );
$api_secret = wpsf_get_setting( 'coinbase', 'general', 'api_secret' );
?>
<div class="wrap">
<div id="icon-options-general" class="icon32"></div>
<h2>Coinbase</h2>
<?php
$this->wpsf->settings();
?>
</div>
<?php
}
function shortcode( $atts, $content = null ) {
$defaults = array(
'name' => 'test',
'price_string' => '1.23',
'price_currency_iso' => 'USD',
'custom' => 'Order123',
'description' => 'Sample description',
'type' => 'buy_now',
'style' => 'buy_now_large',
'text' => 'Pay with Bitcoin',
'choose_price' => false,
'variable_price' => false,
'price1' => '0.0',
'price2' => '0.0',
'price3' => '0.0',
'price4' => '0.0',
'price5' => '0.0',
);
$args = shortcode_atts($defaults, $atts, 'coinbase_button');
// Clear default price suggestions
for ($i = 1; $i <= 5; $i++) {
if ($args["price$i"] == '0.0') {
unset($args["price$i"]);
}
}
$transient_name = 'cb_ecc_' . md5(serialize($args));
$cached = get_transient($transient_name);
if($cached !== false) {
return $cached;
}
$api_key = wpsf_get_setting( 'coinbase', 'general', 'api_key' );
$api_secret = wpsf_get_setting( 'coinbase', 'general', 'api_secret' );
if( $api_key && $api_secret ) {
try {
$coinbase = Coinbase::withApiKey($api_key, $api_secret);
$button = $coinbase->createButtonWithOptions($args)->embedHtml;
} catch (Exception $e) {
$msg = $e->getMessage();
error_log($msg);
return "There was an error connecting to Coinbase: $msg. Please check your
internet connection and API credentials.";
}
set_transient($transient_name, $button);
return $button;
} else {
return "The Coinbase plugin has not been properly set up - please visit the
Coinbase settings page in your administrator console.";
}
}
public function admin_styles() {
wp_enqueue_style( 'coinbase-admin-styles', COINBASE_URL .'
/css/coinbase-admin.css', array(), '1', 'all' );
}
public function widget_scripts( $hook ) {
if( 'widgets.php' != $hook )
return;
wp_enqueue_script( 'coinbase-widget-scripts', COINBASE_URL .'
/js/coinbase-widget.js', array('jquery'), '', true );
}
}
new WP_Coinbase();
?>

2016-08-09 15:27 GMT+01:00 anver <notifications@github.com>:

**Comment by anver** [comment]
Ok here is the solution that worked for me as per the instructions from Kevin one of the blockchain.info support person. 

**Step 1:**
Create a second account using the api and transfer all the funds to this account

**Step 2**
Use the wallet numbers like for the first wallet it's 0 and for the second 1 like so for the "from" and that solved the issue

Thanks

**Comment by KMHouk** [comment]
Awesome, glad it worked out :]

**Comment by ivanskylab** [comment]
I've got same problem.

Here is my code:

$main_password = "my main password";
$second_password = "my second password";
$from = "1N3SZwYjfNokHVH1ABXNXB8x6SMgSB8jQS";
$to = "38ccq12hPFoiSksxUdr6SQ5VosyjY7s9AU";
$amount = 1000000;

$url = "http://127.0.0.1:3030/merchant/058450f4-2456-49e0-84fa-070b3629df8a/payment?password=$main_password&second_password=$second_password&amount=$amount&from=$from&to=$to";
$ch = curl_init();
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_URL, $url);
$ccc = curl_exec($ch);
$json = json_decode($ccc, true);

echo "<pre>";
var_dump($json);
echo "</pre>";

And result:

array(1) {
["error"]=>
string(37) "Error signing and pushing transaction"
}

What wrong I've done?
Do I need Blockchain API key?
I've tried to get an API key but I just received decline messages.
Please help me.
Thank you so much.

**Comment by serjec** [comment]
I have had some troubles myself trying to implement the payments.
I am using API v2 as well, but i haven't seen anywhere a method where i can see the list of the unused addresses.
Beside that i am still strugling about a proper solution for the 20 address limition. i could reuse them after a while like it was suggested in the first comment, but what would happen if 22 users are online at the same time, and some of them want to pay

Any hint would be appreciated

**Comment by VitaliiBoikoSun** [comment]
Is problem solved? Don't know how that happens, but yesterday it worked well and today without any changes in system i get "Error signing and pushing transaction"

**Comment by Crypto100101** [comment]
I am having a similiar issue, when I use your iOS wallet I set the fee to $0.04 and my transaction confirms (takes 4-5 hours) but when I use the service-my-wallet-v3 to set the fee it wont sign unless I specify 0.0001 (I have tried 0.000099) compared to the ~0.000017 fee which goes through on iOS. Did you hardcode the fee when bitcoin was sub 4k ? Please can you abandon limiting fee's.

**Comment by toya999** [comment]
1KU36fxVUskAUHqrxj5kqmuPW6W7k4v1P8

**Comment by gojomo** [comment]
In case it helps anyone else trying to decipher the mysterious "Error signing and pushing transaction" APIException error: it seems one way it can be triggered is by trying to send a very-small amount (like say a few hundred satoshis) to an address, perhaps below some Blockchain 'dust' limit.
