### ISSUE TITLE
private key get back my wallet

### ISSUE THREAD

**Issue by orangkaya15** [blockchain/service-my-wallet-v3#131]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*

**Comment by jtormey** [comment]
Hi, can you please elaborate on what the issue you're having is?

**Comment by orangkaya15** [comment]
how to soft problem watch only  wallet and private key my wallet .
i give you 20%  soft my problem. 
this my wallet watch only and always need private key . crazy how come me not create them ..every wallet changing and changing..always.

**Comment by orangkaya15** [comment]
please help me..now....blockchain ???
watch only (private key???? )1P2vVoU8m2WnvCSKDuFYGhNaFH8f2uawDw 
Watch only( private key???? ) 3CD1QW6fjgTwKq3Pj97nty28WZAVkziNom

**Comment by KMHouk** [comment]
Hi, just trying to clarify, are you trying to find the private key for both of these addresses? Or import it using the service my wallet module?

**Comment by orangkaya15** [comment]
Why your said..like that..what you feel your bitcoin  lost .we talk about the money bro not stone or wood!!!!..the wallet in theft my wallet account. bro..10 bitcoin gone...i have prove to you the wallet theft my bitcoin..bro..i don't know how you talk like..that.. i just need to help ..not to blame me.this wallet bro theft my bitcoin you know!!!!!.1P2vVoU8m2WnvCSKDuFYGhNaFH8f2uawDw this same time the wallet 3CD1QW6fjgTwKq3Pj97nty28WZAVkziNom ..if young to help ..just never mind .dont work services side..

**Comment by iffy8387** [comment]
Trying to find private key for 1Egm467KP9nkg2byFy4ouvXC1qZGeVbEXL (26.37878059 BTC) Watch Only
 Import please help I'm lost
