### ISSUE TITLE
Is it possible to get status of send 

### ISSUE THREAD

**Issue by Lalitpatadiya12** [blockchain/service-my-wallet-v3#134]
Is it possible to get detail and status of transaction which is done using  payment..?

My node version is : 0.12.15
Wallet service version : v 0.22.0

**Comment by jtormey** [comment]
It's not possible to do that directly through this service. To get detailed transaction information, try using our [Blockchain Data API](https://blockchain.info/api/blockchain_api) or our [Query API](https://blockchain.info/q). We even have libraries in several programming languages to make accessing these APIs easier.
