### ISSUE TITLE
blockchain-wallet-service stops working!

### ISSUE THREAD

**Issue by ziomar1** [blockchain/service-my-wallet-v3#136]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*

Hi

my python scrypts gave me these error:
socket.timeout: timed out
the blockchain-wallet-service, return me this:
1474376078927 - error: Maximum concurrent requests for this endpoint reached. Please try again shortly.
1474376138835 - error: ERR_TIMEOUT

No update from my end, all my scrypts worked fine 24/7 for several months untill few minutes ago.

Please help

Service v0.21.4 
Node v5.0.0

**Comment by jtormey** [comment]
We had a brief period of downtime earlier, which might explain the error you saw. Can you confirm that your script is working again?

**Comment by ziomar1** [comment]
Thank you for the quick reply!

Yes now it works!

Have a nice day

**Comment by ziomar1** [comment]
nope false allarm it do not work again!

now it told me 

error: Unknown API Key

please note that I have an unblocked api key!!
