### ISSUE TITLE
Error when including note in outgoing payment

### ISSUE THREAD

**Issue by mladen-stankovic** [blockchain/service-my-wallet-v3#14]
Hi,

When I include note query parameter in outgoing payment I get this error:
"[TypeError: Object �o'X�@���st1/��O�v�<2F&�� has no method 'compare']"

I know that  note can only be attached when outputs are greater than 0.005 BTC so I'm trying to send more than that. If I remove note query parameter everything works fine.

Can you please help?
Thanks

**Comment by jtormey** [comment]
Hi, the `compare` method is used to check two buffers for equality. Looking at the node documentation, it seems that `Buffer.prototype.compare` was not added until v0.11.13. Check your version number by entering `node -v`, if it is lower than v0.11.13 try upgrading node to a newer version and see if that fixes the problem. Thanks.
