### ISSUE TITLE
error: Expected UInt53, got Number 14183421.9999

### ISSUE THREAD

**Issue by kernelpanik23** [blockchain/service-my-wallet-v3#145]
Latest version of Service and Nodejs 0.12.x and 4.x (tried both).

When Making Outgoing Payments i get this error:

`error: Expected UInt53, got Number 14183421.9999`

My request looks like this: 

`http://localhost:3000/merchant/$guid/payment?password=$main_password&second_password=$second_password&to=$address&amount=$amount&from=$from&fee=$fee

Thaks for your help.`

**Comment by jtormey** [comment]
It sounds like you're sending a float instead of an integer. The `amount` and `fee` options are in satoshi, and so must be integers (no decimals).
