### ISSUE TITLE
Estimate transaction size, or apply per-transaction-byte fee

### ISSUE THREAD

**Issue by Informatic** [blockchain/service-my-wallet-v3#147]
Is it possible to easily get estimate transaction size using current API, or is it possible to supply fee per transaction byte?

Currently I'm unable to figure out how much transaction will take to process and what transcation fee would be appropriate, especially when dealing with addresses with lots of dust (at least without manually calculating everything using blockexplorer)

**Comment by jtormey** [comment]
Right now, the api only supports an absolute fee. Although adding a fee-per-byte options (as in the web wallet) is a good idea, I'll work on adding this.

**Comment by vladfaust** [comment]
blockr.io has a Push TX API - http://blockr.io/documentation/api, it allows to decode a raw transaction and to fetch it's vins and vouts. Maybe something similar can be implemented here.

**Comment by jtormey** [comment]
The latest version (v0.24.0) supports a `fee_per_byte` parameter, which allows setting a fee based on satoshi/byte.
