### ISSUE TITLE
Always getting errors

### ISSUE THREAD

**Issue by doktokto** [blockchain/service-my-wallet-v3#15]
"If you are already using our Wallet API, getting started with V2 is as easy as installing the new client service, starting it up, and directing your existing API calls to localhost rather than to blockchain.info."
I can't even install it.
I'm installed npm. Called "npm install -g https://github.com/blockchain/service-my-wallet-v3.git"
Error - no git.
Okay, installed git.
Error - no git.
Okay, changed PATH.
Now it's asking python.

Why, guys? Why I can't just use http get requests? Why there is no just instalation for your new service? Why I have to install tons of things, that I don't need, to use your API? 
I don't even know will it works after installing python or will ask something else.
I just sitting here, searching this packages, searching solutions for this errors.
Why you can't just give to users decide which API they want to use.
"Most importantly, the legacy version of our API will be deprecated at the end of the year as part of planned upgrade."
I received e-mail about in in 16 December.
And now I have 2 days to change my app to use your new API.
There is New Year, holidays, and I'm sitting here with this errors...
And why you said that it's easy, just install it?

**Comment by doktokto** [comment]
![image](https://cloud.githubusercontent.com/assets/5065291/12051173/9972c0d2-af10-11e5-8231-68cbf805ba63.png)
What should I do?

**Comment by JakePrice86** [comment]
Could you include the npm-debug.log file? Errors with node-gyp (on Windows) usually are to do with python not being the the PATH correctly.

**Comment by mjm77** [comment]
Please unsubscribe me from this email chain.

On Wednesday, December 30, 2015, doktokto <notifications@github.com> wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/5065291/12051173/9972c0d2-af10-11e5-8231-68cbf805ba63.png>
> What should I do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blockchain/service-my-wallet-v3/issues/15#issuecomment-167997021>
> .
>


-- 
Sincerely,



Michael J. Morelli
Information Services, Learning Assistant.
Mount Nittany Health, Pennsylvania State University
mjm77@psu.edu
mike.morelli@mountnittany.org
Mobile 814.769.3971

**Comment by doktokto** [comment]
[npm-debug.txt](https://github.com/blockchain/service-my-wallet-v3/files/74851/npm-debug.txt)

**Comment by JakePrice86** [comment]
Yeah, definitely something to do with the proper build tools not being available. I am not on Windows, so I can't help completely, apart from pointing you towards the installation docs for node-gyp.

https://github.com/nodejs/node-gyp#installation

**Comment by mjm77** [comment]
Please unsubscribe me from this email chain

On Wednesday, December 30, 2015, Jake Price <notifications@github.com>
wrote:

> Yeah, definitely something to do with the proper build tools not being
> available. I am not on Windows, so I can't help completely, apart from
> pointing you towards the installation docs for node-gyp.
>
> https://github.com/nodejs/node-gyp#installation
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blockchain/service-my-wallet-v3/issues/15#issuecomment-167999638>
> .
>


-- 
Sincerely,



Michael J. Morelli
Information Services, Learning Assistant.
Mount Nittany Health, Pennsylvania State University
mjm77@psu.edu
mike.morelli@mountnittany.org
Mobile 814.769.3971

**Comment by doktokto** [comment]
Now I'm getting this errors
[npm-debug.txt](https://github.com/blockchain/service-my-wallet-v3/files/74859/npm-debug.txt)

**Comment by doktokto** [comment]
![image](https://cloud.githubusercontent.com/assets/5065291/12051487/b808f7dc-af15-11e5-9108-1384baed952a.png)
![image](https://cloud.githubusercontent.com/assets/5065291/12051497/cb717bc8-af15-11e5-9cb3-9c72f471f3b3.png)
![image](https://cloud.githubusercontent.com/assets/5065291/12051504/da26b246-af15-11e5-9a01-01112635a7b2.png)

**Comment by mjm77** [comment]
Please, for the love of God, unsubscribe me from this email chain.
Mjm77@psu.edu

On Wednesday, December 30, 2015, doktokto <notifications@github.com> wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/5065291/12051487/b808f7dc-af15-11e5-9108-1384baed952a.png>
> [image: image]
> <https://cloud.githubusercontent.com/assets/5065291/12051497/cb717bc8-af15-11e5-9cb3-9c72f471f3b3.png>
> [image: image]
> <https://cloud.githubusercontent.com/assets/5065291/12051504/da26b246-af15-11e5-9a01-01112635a7b2.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blockchain/service-my-wallet-v3/issues/15#issuecomment-168003418>
> .
>


-- 
Sincerely,



Michael J. Morelli
Information Services, Learning Assistant.
Mount Nittany Health, Pennsylvania State University
mjm77@psu.edu
mike.morelli@mountnittany.org
Mobile 814.769.3971

**Comment by JakePrice86** [comment]
@mjm77 Go to thread on Github, click Unsubscribe from Notifications.

**Comment by jtormey** [comment]
Hi @doktokto, it seems like your issue is with the `node-gyp` module, which apparently has a bad reputation for not working on Windows. Please follow the steps outlined [in this article](https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/) to see if that fixes your installation issue, and let me know if it works. In the meantime, I'll look into ways to make the install process easier for our Windows users. Thanks.

**Comment by jtormey** [comment]
With the last update (v0.12), installing has been made much easier. You should be able to install on Windows without a problem now: `npm install -g blockchain-wallet-service`
