### ISSUE TITLE
Error returned even though transaction succeeded

### ISSUE THREAD

**Issue by Informatic** [blockchain/service-my-wallet-v3#150]
*Service v0.19.0, Node v5.5.0*

Hey, I've just received:
```{"error":"Error signing and pushing transaction"}```
when pushing new transaction, even though it has been accepted and published onto the blockchain. What is the reason for that? (Maybe somehow related to #149?)

**Comment by Informatic** [comment]
Actually, it seems to be similar to #142, but the only thing I can see in logs now are these WebSocketErrors.

**Comment by jtormey** [comment]
This problem was caused by a server side issue that was quickly resolved, sorry about that.
