### ISSUE TITLE
Private key???

### ISSUE THREAD

**Issue by iffy8387** [blockchain/service-my-wallet-v3#153]
https://github.com/blockchain/service-my-wallet-v3.(  Private key import 1Egm467KP9nkg2byFy4ouvXC1qZGeVbEXL)watch only

**Comment by paketo** [comment]
But how can I withdraw my BTC

**Comment by jtormey** [comment]
Not sure I understand your issue. Watch only addresses have no private key associated with them, if you want access to the funds in an address, you need to import the private key first.
