### ISSUE TITLE
Insufficient funds :S [SOLVED]

### ISSUE THREAD

**Issue by wmalheiros** [blockchain/service-my-wallet-v3#156]
Service version: 0.22.3
Node version: v5.12.0
npm version: 4.1.1

Hi there!
Since yesterday I'm trying to use this service to send some values to many acounts from my app. So I did not have success. I'm receiving Insufficient funds error message. But my account have funds. 

I saw older posts, but no one solve my problem ;(
I'm receiving this error:

> My specs >>>>>>> My funds. balance: 2016162 SATOSHIS - value to send: 100000 SATOSHIS
Blockchain::APIException: {"error":"Insufficient funds","needed":0.0011,"available":0}
from /home/developer/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/bundler/gems/api-v1-client-ruby-d7fa78884811/lib/blockchain/util.rb:30:in `call_api'

There's something wrong with the service? There something in the API wich I have to do?

Tks

**Comment by jonathanccalixto** [comment]
Hello guys,

I work with @wmalheiros, and I'm here to supplement the problem.
We are using the gem [api-v1-client-ruby](https://github.com/blockchain/api-v1-client-ruby), with the version the branch master. 
We are using an account that has approximately 0.02016162 BTC in a real account for testing. When I look up the balance, using the get_balance method, this value appears in satoshis as @wmalheiros reported, but when I display the addresses, using list_addresses, it lists an address with zero satoshis, all using the reported gem api.
The returned address listing is:
![print_response.png](https://cloud.githubusercontent.com/assets/98915/21546259/ca7f1d5a-cdc4-11e6-8351-5bd6e61714fc.png)
And the source code is:
![source_code01.png](https://cloud.githubusercontent.com/assets/98915/21546309/1a7116c4-cdc5-11e6-97d9-1a7672d772df.png)
![source-code02.png](https://cloud.githubusercontent.com/assets/98915/21546310/1a784340-cdc5-11e6-8c54-1e3e74db545a.png)

**Comment by wmalheiros** [comment]
Very strange. I have a wallet that has multiple addresses that has balance. When I use the server and try to get the addresses, I get an empty array. But if I import an address and send balance to it the system recognizes the address and the balance. Scope of the imported address. Everything is working now, but only with imported addresses.

**Comment by jtormey** [comment]
The `/list` endpoint only lists your imported addresses. It seems like you probably have your balance in an account, which you can access using the `/accounts` endpoint (more on this in the api docs). Does that help?
