### ISSUE TITLE
Service start error

### ISSUE THREAD

**Issue by me4onkof** [blockchain/service-my-wallet-v3#158]
Node: v0.10.46
Blockchain wallet; 0.22.3

I cant start bitcoin wallet service showing me this error:

![c1bfcc197d584021915392fd9c02605a](https://cloud.githubusercontent.com/assets/16834475/21601776/5e9f9346-d196-11e6-9750-1f55893fed5b.png)

**Comment by jtormey** [comment]
The minimum Node version is v0.12, can you upgrade and try again?

**Comment by me4onkof** [comment]
yes i fixed it but now awaiting for API code

**Comment by Myleskgifford** [comment]
git@github.com:blockchain/service-my-wallet-v3.git
