### ISSUE TITLE
Very hard time on Windows - still not working...

### ISSUE THREAD

**Issue by JKalcher** [blockchain/service-my-wallet-v3#16]
Hi!

First of all – I like your idea, I like blockchain wallets and your services, especially the API (the “old” one). 
This new APIS is a nightmare for Windows / .net developers.
Sounds so easy and ends up in frustrating hours… 
Did not use node.js – so I installed that
Got an error on npm, missing GIT – so I installed that as well
Took some time to fix the path problem – next error on node-gyp
So I installed Python as well…
And now I end up with an error telling me that there is a problem with the blockchain-wallet-client package (see trace output below / file attached).

Guys, that is really frustrating – I am a professional developer for years, yes I am mainly on Windows, and yes I do understand that the bitcoin world is not focusing Windows that much…

I really hope that you come back asap, and that you can help.
Additionally the documentation on your website is confusing as well. So I do not understand why you change the API model in that way. The expiring API really was fine.

Anyhow, thanks for your support. By that, I am running Windows 10, Visual Studio Enterprise 2015 (I did not have problems with Python / node-gyp, after installing Python version 2.7.10)

Joachim

14371 error blockchain-wallet-client@3.3.3 postinstall: `cd node_modules/sjcl || cd ../sjcl && ./configure --with-sha1 && make`
14371 error Exit status 1
14372 error Failed at the blockchain-wallet-client@3.3.3 postinstall script 'cd node_modules/sjcl || cd ../sjcl && ./configure --with-sha1 && make'.
14372 error Make sure you have the latest version of node.js and npm installed.
14372 error If you do, this is most likely a problem with the blockchain-wallet-client package,
14372 error not with npm itself.
14372 error Tell the author that this fails on your system:
14372 error     cd node_modules/sjcl || cd ../sjcl && ./configure --with-sha1 && make
14372 error You can get information on how to open an issue for this project with:
14372 error     npm bugs blockchain-wallet-client
[npm-debug.zip](https://github.com/blockchain/service-my-wallet-v3/files/75314/npm-debug.zip)

**Comment by jtormey** [comment]
Hi @JKalcher, sorry about the installation issues, some of the libraries we use have a build step (that's what node-gyp is for) which doesn't play nicely with Windows. With the last update, these steps aren't necessary anymore and you can install directly from npm (rather than github), so things should go more smoothly.

Try installing v0.12 of the service like so:
`npm install -g blockchain-wallet-service`

Thanks for your patience, I hope that helps.

**Comment by minha361** [comment]
My npm version is 2.15.1 Node version is v4.4.3 CentOS release 6.7 (Final) When I run

npm install -g blockchain-wallet-service
Console show error:

gyp ERR! build error gyp ERR! stack Error: make failed with exit code: 2 gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23) gyp ERR! stack at emitTwo (events.js:87:13) gyp ERR! stack at ChildProcess.emit (events.js:172:7) gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12) gyp ERR! System Linux 2.6.32-573.el6.x86_64 gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" gyp ERR! cwd /usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain.info/node_modules/ws/node_modules/utf-8-validate gyp ERR! node -v v4.4.3 gyp ERR! node-gyp -v v3.3.1 gyp ERR! not ok
Then I try to run service "blockchain-wallet-service start --port 3000" and try to connect to the service

curl -X POST 'http://localhost:3000/api/v2/create?api_code=myCode&password=aPassword'
In the service console has message

Error: RNG.run [ReferenceError: XMLHttpRequest is not defined] 1462457502389 - error: Error generating the entropyReferenceError: XMLHttpRequest is not defined
Please tell me how to fix this Issue The blockchain-wallet-service require node >= 0.12.0 and npm >= 2.12.0, < 3.0.0 Here is url that I use https://github.com/blockchain/service-my-wallet-v3 Thanks very much!

node.js
