### ISSUE TITLE
jamiepg3

### ISSUE THREAD

**Issue by jamiepg** [blockchain/service-my-wallet-v3#160]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*

**Comment by jtormey** [comment]
What's the issue you're having?

**Comment by exportingood** [comment]
have been tranfer my bitcoin from my miner and it will took more than 24
hours to receive and it will not deliver the coin can u hwlp me out

**Comment by jtormey** [comment]
@exportingood doesn't seem like your issue is specific to this project. Are you sure your miner is sending to the correct bitcoin address? If it is, are you including a high enough fee with the transaction?

**Comment by exportingood** [comment]
no

**Comment by sonphan66** [comment]
Yes.here
