### ISSUE TITLE
Watchonly 

### ISSUE THREAD

**Issue by Ursulaarmas** [blockchain/service-my-wallet-v3#162]
What happens if I delete that account? Dont have privatekey and cant get it any where? Does someone wanna buy whole wallet 220€ theres about 250€ ¿¿

**Comment by jtormey** [comment]
Watch only addresses are addresses that do not have the private key stored with them. If you want to spend funds from a watch only address, you need to know the private key (this is to prove that you own the funds in the address). Deleting a watch only address is safe, as long as you still have the private key stored elsewhere.

**Comment by Ursulaarmas** [comment]
Its safe to delete if I got privatekey...why I would ask this things if I
got privatekey? I got everything Else. .what happend funds when deleted if
dont have privatekey? Tried recovery first disable 2nd pw like prefered but
it only give new adress no funds were transfered.. i got this wallet from
someone who owned me seems like he still own me that money...but isnt
privatekeys created from that bt adress can I some how recreate it?tried
also another account pk but didnt work

23.1.2017 16.40 "Justin Tormey" <notifications@github.com> kirjoitti:

**Comment by jtormey** [comment]
If the funds are in an address marked as "watch only", they can't be recovered. You will have to get the private key from whoever gave you the wallet.

**Comment by Ursulaarmas** [comment]
He dont got it I dont know how he even managed to create watchonly..but if
I deposit More money to that wallet can I get pk then? And where bitcoins
go they tell me that those neverdie😀😂 do blockchain got those?though if I
delete it u get 250 and give me 200 to normal account? And why recovery of
funds didnt work only new wallet camera?

23.1.2017 17.27 "Justin Tormey" <notifications@github.com> kirjoitti:

**Comment by Ursulaarmas** [comment]
F**ck it shows here when email in 😉 anyone buy wallet for 200€u get wallet and funds250€😎

**Comment by Ursulaarmas** [comment]
What is that camera there :p

**Comment by jtormey** [comment]
Blockchain doesn't store any of your bitcoins, sorry but if you don't have the private key then funds in that address can't be sent. Wallet recovery will only recover funds stored in your accounts, which is why we discourage users from storing btc in imported addresses.
What camera are you referring to?

**Comment by Ursulaarmas** [comment]
Yeah I dont know its this autofill or what its in UK maybe come..so funds
didnt move when I recover with prhase only got new wallet.. someone told to
disable 2nd pw and then recovery but didnt work

23.1.2017 18.15 "Justin Tormey" <notifications@github.com> kirjoitti:

Blockchain doesn't store any of your bitcoins, sorry but if you don't have
the private key then funds in that address can't be sent. Wallet recovery
will only recover funds stored in your accounts, which is why we discourage
users from storing btc in imported addresses.
What camera are you referring to?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/blockchain/service-my-wallet-v3/issues/162#issuecomment-274533144>,
or mute the thread

**Comment by Ursulaarmas** [comment]
Now got privatekey but after set transfer  it ask this... Input your pw for privatekey. It get stuck and kick me out after awhile from wallet....?

**Comment by Ursulaarmas** [comment]
Whats this 2nd pw wallet pw? This come after try move moneys

23.1.2017 18.19 "Perttu Portti" <pertttu@gmail.com> kirjoitti:

**Comment by jtormey** [comment]
Is the private key you're using a BIP38 password protected key?

**Comment by Ursulaarmas** [comment]
I dont know I created it.. and Lost it but its somewhere in destkop
copypaste it
Good bisnes to sell people privatekeys if Lost or Forgotten..?

23.1.2017 21.58 "Justin Tormey" <notifications@github.com> kirjoitti:

**Comment by jtormey** [comment]
I wouldn't recommend ever buying a private key, because there's always the chance that the person you bought it from could reclaim the funds. It's much safer to have the bitcoin sent to an address that only you own.

If you don't have an issue with this project (service-my-wallet-v3) in particular, do you mind closing this issue?

**Comment by Ursulaarmas** [comment]
Closer if want

24.1.2017 17.40 "Justin Tormey" <notifications@github.com> kirjoitti:

I wouldn't recommend ever buying a private key, because there's always the
chance that the person you bought it from could reclaim the funds. It's
much safer to have the bitcoin sent to an address that only you own.

If you don't have an issue with this project (service-my-wallet-v3) in
particular, do you mind closing this issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/blockchain/service-my-wallet-v3/issues/162#issuecomment-274839902>,
or mute the thread

**Comment by jtormey** [comment]
Thanks, feel free to reach out to us at https://support.blockchain.com if you have any more issues.
