### ISSUE TITLE
"Maximum concurrent requests for this endpoint reached..." error very frequent

### ISSUE THREAD

**Issue by albydeca** [blockchain/service-my-wallet-v3#163]
*Service v0.22.0, Node v5.11.1*

Hi,

I'm getting the following error "Maximum concurrent requests for this endpoint reached. Please try again shortly" multiple times today. I'm using the following calls, in quick succession of max 2 per second:

- `/merchant/:guid/payment`

- `/merchant/:guid/balance`

- `/merchant/:guid/list`

- the `blockexplorer` module in `api-v1-client-python`

I'm finding that operations that used to happen without problems are throwing this error, plus `blockexplorer` is occasionally throwing "Read operation timed out", something that I've never seen before.

Looking online, there seems to be no clear answer as to why these errors happen. All calls where an API code is required or optional have my API code.

Could you please tell me why these problems could be occurring?

Thanks very much,
Alberto

**Comment by jtormey** [comment]
Hi,

The "Maximum concurrent requests" error is a global rate limit that appears when our servers are under higher stress than usual. You're less likely to see it if you make API calls less frequently. When it does happen, usually trying again a few seconds later will work.

I haven't seen the "Read operation timed out" problem, will look into it. Have you noticed any calls in particular that cause it?

**Comment by albydeca** [comment]
Ok thanks for the explanation!

The "read operation timed out" problem happens when an APIException is caught on line 27 of `util.py` in the blockchain pip package (blockchain==1.1.1). The calls I make are typically `blockexplorer.get_tx(id)` and `blockexplorer.get_address(BTC_address)`.

Hope this helps. I've only seen this exception yesterday morning GMT together with the "Maximum concurrent requests" so it could just be due to server overload at that time.

**Comment by jtormey** [comment]
Thanks for the info. You're right, the read timeout is probably also a server load issue. We're looking into it further, but for now it seems to be pretty infrequent and hopefully doesn't cause too many issues for you.

**Comment by kireerik** [comment]
#267

**Comment by number9387** [comment]
what is the command to make the python script pause and wait a few seconds instead of just crashing when encountering this error.  I've already used util.TIMEOUT = int to no avail regarding this particular error
