### ISSUE TITLE
Mismatch between balance taken from /balance endpoint and sum of spendables

### ISSUE THREAD

**Issue by albydeca** [blockchain/service-my-wallet-v3#167]
*Service v0.22.0, Node v5.11.1*

Hey, sorry it's me again.

I have noticed a mismatch this morning between methods of fetching the balance for one BTC address I own.

My public address is 1Lu1ejJQrEHiuzNi5Ud789m6x4XgkAk5Qh

- The `/balance` endpoint of this API service returns 0.00364109 BTC

- The Blockchain.info dashboard shows 0.00364109 BTC

- The third method, used by a service I use called "Blockcerts" (blockcerts.org) calculates the balance as a sum of spendables for that address. It fetches those spendables by calling URL:
`http://blockchain.info/unspent?active=1Lu1ejJQrEHiuzNi5Ud789m6x4XgkAk5Qh`
and sums up the `coin_value` attributes of each. This method returns 0.00027063 BTC.

I'm not sure if this is an actual error with the third method or if effectively calculating balance is sometimes not as simple as summing up spendables. I don't have the Bitcoin knowledge to answer this.

I can say however that I tried doing the same for two other wallets, and there was no mismatch. One of the wallets has address 17kMx1oqoBSGpiJaFbh24NukRGuXsYT3HQ.

Can you please tell me what is going on? I can change the behaviour of Blockcerts as I'm working on a forked copy but I'd rather not change core behaviour of third party code.

Thanks very much!
Alberto

**Comment by jtormey** [comment]
Hmm, I'm having some trouble reproducing this issue.

I've checked all the endpoints we have for getting an address balance and they all agree that the balance is `0.00027063 BTC`.

https://blockchain.info/balance?active=1Lu1ejJQrEHiuzNi5Ud789m6x4XgkAk5Qh
https://blockchain.info/multiaddr?active=1Lu1ejJQrEHiuzNi5Ud789m6x4XgkAk5Qh
https://blockchain.info/address/1Lu1ejJQrEHiuzNi5Ud789m6x4XgkAk5Qh?format=json

I also imported it as a watch-only address to a wallet, and tried using it with the endpoints provided in this service (`/balance` and `/address_balance`). They both respond with the correct balance.

Is it possible that there are other addresses / accounts in your wallet that are adding to the balance? That would explain why the balance is higher in the dashboard and in `/balance`.

Can you try using [`/address_balance`](https://github.com/blockchain/service-my-wallet-v3#fetch-address-balance) to get the balance of just that address specifically?

**Comment by albydeca** [comment]
Thanks for your help!

I've understood the problem. That wallet has an address to which I mistakenly sent funds manually. What I meant to do was send funds to the IMPORTED address (the one reported above), which if I am not mistaken is the one returned in the API response of `/api/v2/create`, because that is what I fetch from the API response and save to my DB for later use.

All BTC transfers within my app are made to and from that imported address. I had to send funds manually that one time and I accidentally sent them to the non-imported address. This would explain the mismatch.

**Comment by jtormey** [comment]
Great! Glad things are working as expected.
