### ISSUE TITLE
Using with Proxy

### ISSUE THREAD

**Issue by b12k** [blockchain/service-my-wallet-v3#179]
Greetings!
I'm hosting Service My Wallet on Heroku.
As you may know Heroku has a dynamic IP for its dynos.
To have a Static IP I need to use a proxy service "Fixie" or "Proximo" or whatever...
Can you give me a hint how can I do that?

Thank you in advance!

**Comment by mimica12345** [comment]
How I get my money?

**Comment by b12k** [comment]
@mimica12345 
How to use My Wallet Service behind a proxy.

**Comment by Theeeus** [comment]
@b12k Greetings!
Were you able to solve the proxy issue on Heroku? I'm trying to do it as well, so any direction would be appreciated.

**Comment by b12k** [comment]
Hello @Theeeus 

Ufff its been a while... =)

If I'm not mistaken solution was:

White list **_ALL_** possible IPs of Heroku servers of your region. Check 👉 [Heroku Docs](https://help.heroku.com/JS13Y78I/i-need-to-whitelist-heroku-dynos-what-are-ip-address-ranges-in-use-at-heroku). You would need to manually map/filter that AWS json to a comma separated list and provide it in Blockchain Wallet settings. There is (was?) such possibility some where.

It may look like a "potentially insecure" solution, but:
- Its just a wallet client which exposes no critical data
- Wallet URL should not be exposed else where
- I forked client and added a verification of the "super secret" header with some "access token" for every incoming request 

Hope it helps.

Cheers!

**Comment by Theeeus** [comment]
Thanks @b12k. 

I had implemented this same solution and it's nice to hear that I was on the right way and specially that it's not a security risk.

Cheers!
