### ISSUE TITLE
"Error": "Insufficient funds"

### ISSUE THREAD

**Issue by mosqueiro** [blockchain/service-my-wallet-v3#195]
- Node v0.12.0
- blockchain-wallet-service 0.23.3

I think there must be something wrong.
I am using the v2 API, it does not create wallet, I received the same error:
{Error: "Unknown API key"}

There is balance and I get the API value:
{"Balance": 160960}

But when I try to make a payment, it returns me that there is no balance.
{"Error": "Insufficient funds", "needed": 0.00010808, "available": 0}

**Comment by jtormey** [comment]
For your first issue, do you know if your api key has permission to create wallets? If you don't know, you can create an issue at https://support.blockchain.com, our great support team would be happy to help.

As for your second issue, are you including a "from" parameter in your request? This is required when trying to send from one of your HD accounts.
