### ISSUE TITLE
Gulamnabi m qureshi

### ISSUE THREAD

**Issue by umefa2478** [blockchain/service-my-wallet-v3#196]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*

**Comment by umefa2478** [comment]
How I work give me advise  I do as you wiss

**Comment by umefa2478** [comment]
I am redy do work evry time just sow it

**Comment by umefa2478** [comment]
New gie work me I want work only as your advise

**Comment by umefa2478** [comment]
Don't West my time

**Comment by umefa2478** [comment]
Yesterday I do work is wrong or right sow me

**Comment by jtormey** [comment]
Not sure I understand. If you have an issue related to this repo, please open a new issue with a clear description so that I can help. Closing this issue as off-topic.
