### ISSUE TITLE
installation issues in wallet service

### ISSUE THREAD

**Issue by padma-sree** [blockchain/service-my-wallet-v3#198]
Someone please help me with the installation

npm version:4.4.4 
node version:v7.7.4
wallet service version:0.23.3
![capture](https://cloud.githubusercontent.com/assets/24808092/24325061/a7235bb4-11b7-11e7-8f8e-56c939ef8f54.PNG)
![capture1](https://cloud.githubusercontent.com/assets/24808092/24325062/a7262efc-11b7-11e7-9731-4bfa334f5298.PNG)

**Comment by jtormey** [comment]
Try running it with `--no-optional`

**Comment by Gagan0436** [comment]
@jtormey It worked for me! Thanks :D
