### ISSUE TITLE
External Connections

### ISSUE THREAD

**Issue by ConKreter** [blockchain/service-my-wallet-v3#200]
"Note that blockchain-wallet-service is designed to be run locally on the same machine as your application and therefore will only accept connections from localhost. If you modify this service to accept external connections, be sure to add the appropriate firewall rules to prevent unauthorized use."

Where is that bit in the code which limits the scope only to localhost? I would like to change that on my version.

**Comment by jtormey** [comment]
You can change the IP the service is bound to with the `--bind` option. We don't recommend doing this, because unless you have security measures in place, it could expose the service API publicly. Instead, consider creating your own public API, which connects to this service via localhost.

**Comment by ConKreter** [comment]
if you do the --bind with the external server IP. Then this server can connect but noone else?

**Comment by jtormey** [comment]
The IP you pass to `--bind` is the IP you want the service to be accessible from. `--bind 127.0.0.1` means that it can only be accesses through localhost. If you do `--bind <you machine's ip>`, then it will be available to any system that can access that machine.
