### ISSUE TITLE
Error: Error decrypting wallet, please check that your password is correct

### ISSUE THREAD

**Issue by Duanthse03268** [blockchain/service-my-wallet-v3#205]
I'm using NodeJS 4.8.2 (x64) and NPM 2.15.11 when i connect to my wallet via

> http://localhost:3000/merchant/$guid/list?password=$password

. I got the error
**Error decrypting wallet, please check that your password is correct**.
I installed JDK 8 & JRE 8 and run on **window server 2012** . What am i missing ?
I sure my password is correct because i tried to login many time. But i don't know why that got error

**Comment by Duanthse03268** [comment]
I resolved need to **uninstall BlockChain API after install java jdk then install node-gyp and reinstall API**.

**Comment by kingkyle09** [comment]
hello,,,, was this issue resolved already? I got same problem and i don't know how to solve it. please help

**Comment by Duanthse03268** [comment]
Check my solution above

**Comment by kingkyle09** [comment]
where can I uninstall API? what link should I open?

**Comment by jtormey** [comment]
You can uninstall the service with `npm uninstall -g blockchain-wallet-service`

**Comment by kingkyle09** [comment]
please give me a link please?

**Comment by jtormey** [comment]
I'm not sure what you mean, what kind of link are you looking for? Here are the docs for installation: https://github.com/blockchain/service-my-wallet-v3#installation

**Comment by kingkyle09** [comment]
thank you for the reply.... is this proven solution to solve the error?
_Error decrypting wallet, please check that your password is correct_
i am very sure that i am using the right password

**Comment by jtormey** [comment]
That error usually happens when there's an issue with the installation. Does anything in the [Troubleshooting](https://github.com/blockchain/service-my-wallet-v3#troubleshooting) section solve your issue?

**Comment by kingkyle09** [comment]
i am using blockchain.info to open my account,,,, is that applicable solution to this site?

**Comment by Duanthse03268** [comment]
This error due to u didn't install JDK. You have to install JDK before install blockchain api. If you installed blockchain before jdk, you have to uninstall blockchain to make sure you install jdk first

**Comment by kingkyle09** [comment]
what is JDK? this is my process to open my wallet
1. i open www.blockchain.info
2. then enter my identifier and password then the error appear
   I been using the same password for 6 months and did not change it but suddenly the error came.
i did not install anything like blockchain api,,,, 

do i need to install JDK? where should i install it?

**Comment by Duanthse03268** [comment]
https://www.npmjs.com/package/jdk check it

**Comment by kingkyle09** [comment]
i still not solve the issue,,, I don't know what to install and uninstall,,,,hope somebody help me in more detailed way,

**Comment by Duanthse03268** [comment]
add my skype duanthse03268@gmail.com i can help you :D

**Comment by strapa** [comment]
Duanthse, I have the same problem, Im a noob, help me. I log on the site, I put my password, I accept the verification on my e-mail and appears: "Error decrypting wallet, please check that your password is correct", why? If It is a wrong password, why I reacive a verification e-mail, please, help me, I need help.

**Comment by kingkyle09** [comment]
I am adding you in skype
On Monday, July 24, 2017, 12:06:40 PM GMT+8, strapa <notifications@github.com> wrote:


Duanthse, I have the same problem, Im a noob, help me. I log on the site, I put my password, I accept the verification on my e-mail and appears: "Error decrypting wallet, please check that your password is correct", why? If It is a wrong password, why I reacive a verification e-mail, please, help me, I need help.

**Comment by strapa** [comment]
What? I dont understand

**Comment by strapa** [comment]
My skype: joaoxsxs

**Comment by strapa** [comment]
My skype: joaoxsxs

E-mail: strapacontact@gmail.com

Please, anyone help

**Comment by Duanthse03268** [comment]
This is only for developer using block chain api pls if you are login to blockchain.info you are not in this issue

**Comment by strapa** [comment]
But It's the same error, please man...I need help, I think you can help me

**Comment by strapa** [comment]
You help King, right?

**Comment by strapa** [comment]
I just need that, I have so money on that site, I write a e-mail to you, check, please

**Comment by strapa** [comment]
Just lock and tell me If you can help, please...

**Comment by Duanthse03268** [comment]
Contact the blockchain.info support

**Comment by strapa** [comment]
I'm trying but he dont give a shit...Im waiting, some guys on foruns said he cant help...But my error its noy my foud
