### ISSUE TITLE
API Key not allowing to create Wallet

### ISSUE THREAD

**Issue by swarsaha** [blockchain/service-my-wallet-v3#209]
Version: *Service v2.12.0, Node v0.12.4

Hi,
I have received API key. But with the key, when I am trying to call http://localhost:3000/api/v2/create api end point for wallet creation with the required parameters as mentioned in the script, I am always receiving error "Unknown API key".
My installation is fine, since I am able to use other APIs.

Looking forwards for your response and other valuable guidance.

Thanks and Regards,
Swarup

**Comment by jtormey** [comment]
You might not have the "Create Wallets" permission set on your API key. Please reach out to me directly (justin@blockchain.com) so I can help with that.
