### ISSUE TITLE
Address not found in wallet

### ISSUE THREAD

**Issue by IainStrath** [blockchain/service-my-wallet-v3#210]
Hello,

I access this link 2 times: http://127.0.0.1:3000/merchant/***my-id***/new_address?password=***&second_password=&label=
And receive 2 IP addresses. Then I send money to fist address. But But when I log into the wallet, I only see the second address. And my wallet is empty.

I tried adding the first address to my wallet but it show "Watch Only"
I know that, to control this address, I need a private key

So, the questions:
- Why this error occurs? The address is created but not displayed in the wallet.
- How to have the private key (I created an address using the API)

Please help me, I can not get my money :(

blockchain-wallet-service 0.23.3, Node v7.9.0

**Comment by jtormey** [comment]
That's very strange, were there any errors in the console output?

**Comment by IainStrath** [comment]
No, everything is ok. I tried again many times but this error does not happen again. Who can I contact for support?

**Comment by jtormey** [comment]
Hm, I'm not able to reproduce either, even when creating 100's of addresses at the same time... Will have to investigate further. In the meantime, please contact me directly (justin@blockchain.com), so I can help you with recovery.

**Comment by Nhey31** [comment]
hi jtormey i will email u and wiull ask u something about my account if that ok for u
