### ISSUE TITLE
Dynamic Fee Calculation

### ISSUE THREAD

**Issue by ConKreter** [blockchain/service-my-wallet-v3#212]
Is there a way to set a Fee like 130 Sat/B or something? When you do a transaction you dont know the size since that depends on how many addresses are used to facilitate the process. So its difficult to choose a fixed Fee. The Blockchain.info wallet does support an automatic calculation. Is something like this here possible?

Thanks a Lot.

**Comment by jtormey** [comment]
Right now, no, but there will soon be a way to specify fee per byte instead of a static fee.

**Comment by jtormey** [comment]
v0.24.0 (now published) includes a `fee_per_byte` parameter, so to specify 130 sat/b, send `fee_per_byte=130`.
