### ISSUE TITLE
Multiple HD accounts in same wallet not working

### ISSUE THREAD

**Issue by ConKreter** [blockchain/service-my-wallet-v3#214]
Hi,

I used /merchant/:guid/accounts/create to create a new HD account. The result look very valid.

This is not visible via browser and wallet is also not visible via /merchant/:guid/accounts or via /merchant/:guid/accounts/xpubs

Then I created a new HD account via browser which is also not visisble via /merchant/:guid/accounts

I even sent money on it which is visible via browser but not via API.

I initially created this account via browser and whitelisted the service IP. This might be part of the problem.

Please advise.
Thanks

**Comment by jtormey** [comment]
Hmm this might be an issue syncing the newly generated account with the server, possibly because of the IP restriction... Looking into it now.

Are the first account shown by the service and the first account in the browser the same?

If you generate a new account in the browser, does the xpub of the new account match that in the response to /accounts/create? (It should, since accounts are generated deterministically)

**Comment by ConKreter** [comment]
When I create an account with /accounts/create?
then its not visible ANYWHERE. Its not visible in browser and also not in /merchant/:guid/accounts

The callback of the function was this:

{"label":"Test31","archived":false,"xpriv":"****","xpub":"****","address_labels":[],"cache":{"receiveAccount":"****","changeAccount":"****"}}
**** were valid looking data, I just removed it.

When I create an account via browser then its visible via browser with a valid xPub but its not visible via /merchant/:guid/accounts
there is only the default Account that was in there since I created the wallet.

**Comment by ConKreter** [comment]
"Are the first account shown by the service and the first account in the browser the same?"

Yes the first account in the /accounts and in browser are identical, so its the same wallet (which makes sense)

**Comment by jtormey** [comment]
@ConKreter I just published v0.23.4, which contains a fix that makes sure the service does a full wallet sync before sending the http response. Could you try again to see if this issue is solved in the new version?

**Comment by ConKreter** [comment]
The HD account I created via browser is now visible, which is awesome. I havent tested the creation of a new one via API yet. I will do so in a bit.
I saw you did a commit regarding dynamic fees. Is that already in the nodejs module I just loaded?

**Comment by ConKreter** [comment]
Creation via API also works. Thanks a lot for the patch, highly appreciated

**Comment by jtormey** [comment]
Nice! Glad it's working.

The dynamic fee feature hasn't been released yet, I'm going to put it in the next minor version, since it involves changes to the API. That will be released sometime today, I'll comment in #212 when I've done that.
