### ISSUE TITLE
Service v0.24.0

### ISSUE THREAD

**Issue by sergek99** [blockchain/service-my-wallet-v3#220]
1) при установке обновления сервис не запускался (не хватает пакетов
es6-promise isomorphic-fetch sjcl bip39 unorm pbkdf2)

2) не работает api

**Comment by jtormey** [comment]
The issue is most likely that you are using npm 3. Unfortunately, this project still requires npm 2. To change version, you can run `npm install -g npm@2`.

**Comment by jtormey** [comment]
As of v0.26, the service can be installed with npm 3.
