### ISSUE TITLE
Can't Access to IOS App and my old wallet 

### ISSUE THREAD

**Issue by FreeWorld123** [blockchain/service-my-wallet-v3#225]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*

Hello,

I hope you will help me as fast as possible.

Background:
In September last year i sent to my wallet (IOS App) ~ 1 Bitcoin, but since that i'm not able to Login with the App anymore.

If i wan to enter my Passwort. This Message pop-up:

(german) Fehler: ungültige Bitcoin-Adresse
(translate to englisch): ~invalid Bitcoin-Address

I have a 16-Phrases Passwort noticed.

I am not sure, if i have created a new Blockchain Wallet but the Adress where i had to sent the BTC is now in my Wallet (webacces) saved under "watch-only address. I am not able to sent the coins but the Coins are still on this Wallet.

If i login now in my wallet (web) i have only a 12-Phrases Passwort.

Could you please Help me? Maybe threw PM.

The blockchain Support promised me to get help here.
Maybe my coins are still on the blockchain App? Because if i enter a wrong Passwort there comes another error Message as i get 

Thank you

**Comment by jtormey** [comment]
Not relevant to this project. Issue has been moved to our [support center](https://support.blockchain.com).
