### ISSUE TITLE
I can't login to the wallet

### ISSUE THREAD

**Issue by html5-ninja** [blockchain/service-my-wallet-v3#23]
this what I'm getting when I try to connect 

{
error: "Already trying to login to a wallet. To change wallets, try again in a moment"
}

on console I got this 
ERR_LOGIN_BUSY

**Comment by html5-ninja** [comment]
my fault , it work perfectly , I added my server ip to the whit-list in alpha wallet , you should note that in doc :)

**Comment by jtormey** [comment]
Will do. Thanks!
