### ISSUE TITLE
unable to create session when sending payment

### ISSUE THREAD

**Issue by krustyfur** [blockchain/service-my-wallet-v3#230]
Service v0.24, v0.25.1, Node 6.10.2

I was getting "Unable to establish session" for a couple of days now since a server reboot, after using it with (minimal) trouble for a week+. It wasn't until I did a get balance on the wallet that I was able to send a payment.

No API key used (haven't received any response after trying to get one 2 weeks ago).

**Comment by jtormey** [comment]
Not completely sure what might be causing this one. I just released a patch version (0.25.2) that adds extra logging around the login process. Could you try again with that version to see if it provides any extra info? To enable debug log messages, pass `--log-level debug`.

**Comment by krustyfur** [comment]
This is immediately after upgrading to 0.25.2 and restarting the service. The payment attempt was via [the java client](https://github.com/blockchain/api-v1-client-java) which I modified to add support for your recent feePerByte addition to the service.

```
Jun  5 21:15:16 XXX blockchain-wallet-service: 1496697316011 - debug: Logging in
Jun  5 21:15:16 XXX blockchain-wallet-service: undefined
Jun  5 21:15:16 XXX blockchain-wallet-service: 1496697316324 - debug: Failed to establish session, retrying...
Jun  5 21:15:16 XXX blockchain-wallet-service: 1496697316500 - debug: Failed to establish session, reason: Unknown API Key
Jun  5 21:15:16 XXX blockchain-wallet-service: 1496697316521 - error: ERR_SESSION

```

Then connecting to the service directly via telnet to get the balance on the same wallet worked
```
Jun  5 21:24:33 XXX blockchain-wallet-service: 1496697873872 - debug: Logging in
Jun  5 21:24:34 XXX blockchain-wallet-service: 1496697874159 - debug: Created new session token
Jun  5 21:24:34 XXX blockchain-wallet-service: 1496697874322 - debug: Fetched wallet
Jun  5 21:24:34 XXX blockchain-wallet-service: 1496697874525 - debug: Decrypted wallet
Jun  5 21:24:34 XXX blockchain-wallet-service: 1496697874539 - debug: Fetching wallet history
```

Trying the send payment AGAIN via the java client subsequently worked. 
```
Jun  5 21:24:33 XXX blockchain-wallet-service: 1496697873872 - debug: Logging in
Jun  5 21:24:34 XXX blockchain-wallet-service: 1496697874159 - debug: Created new session token
Jun  5 21:24:34 XXX blockchain-wallet-service: 1496697874322 - debug: Fetched wallet
Jun  5 21:24:34 XXX blockchain-wallet-service: 1496697874525 - debug: Decrypted wallet
Jun  5 21:24:34 XXX blockchain-wallet-service: 1496697874539 - debug: Fetching wallet history
Jun  5 21:26:44 XXX blockchain-wallet-service: 1496698004618 - debug: Fetching wallet history
Jun  5 21:26:59 XXX blockchain-wallet-service: 1496698019222 - debug: Transaction published hash=55de18a004b0da49a8620295c0342ece66af46c707298e7b71c3009fd623fa82
Jun  5 21:26:59 XXX blockchain-wallet-service: 1496698019223 - debug: Recording smwv3 event name=send
```

The "undefined" log message in the first block is consistent with previous errors too. 

Hope this helps

**Comment by jtormey** [comment]
I just tested this with the java client, could it be that you're passing an empty string as the apiCode parameter to the Wallet constructor?

This gives me the same error that you have:

```
Wallet w = new Wallet("http://127.0.0.1:5000/", "", myGuid, myPassword);
```

However, when I pass `null`, the api key is omitted from the request and the call succeeds:

```
Wallet w = new Wallet("http://127.0.0.1:5000/", null, myGuid, myPassword);
```

**Comment by krustyfur** [comment]
It should be `null` always as it isn't set in the configuration. 

In any case, it is the same configuration object in memory used for the call that is failing before direct access, to each subsequent call that succeeds (for which a new Wallet is created each time).

**Comment by jtormey** [comment]
That would be really useful, thanks.

Internally, only the API key that is present when a wallet is initially logged into is used. So it would make sense that all calls fail when passed an invalid API key, while subsequent calls after a successful login are fine (even when they're also passed an invalid API key).

**Comment by krustyfur** [comment]
It was an empty string and not a null after all, sorry about that.

As a design issue, if the local service is only honoring the API key on the first call it is used on, why isn't it part of the configuration for the service instead? Requiring it to be passed in on each call but essentially ignoring it is a confusing design.

**Comment by jtormey** [comment]
You're right, it would be better to allow passing it when starting the service. It was designed this way to be backwards compatible with our hosted API (which did require the API key to be sent with each request). I'll make it so that the key can be passed as an option at startup.
