### ISSUE TITLE
Service is not working

### ISSUE THREAD

**Issue by tinodj** [blockchain/service-my-wallet-v3#235]
Hi,

this service is not working since yesterday. In the log I can see the following: 

1496712861511 - error: WebSocketError message=socket hang up, code=ECONNRESET
1496729928147 - error: <!DOCTYPE html> ....
1496730242103 - error: <!DOCTYPE html> ....

**Comment by jtormey** [comment]
Not working in what way? Can you make sure that requests are able to reach blockchain.info from wherever you're running the service? ECONNRESET means that the connection was ended abruptly.

**Comment by tinodj** [comment]
Hi, I am pretty sure I can reach blockchain.info - because for one wallet it is working, and for the other it is saying error: and then printing some html. It prints `<!DOCTYPE html>` and so on ... This is also in that html: 

Looks like our site is down. We're working on it and should be back up soon.

**Comment by tinodj** [comment]
also, this is in the HTML:

` <p>The web server reported a bad gateway error.</p>
  <ul class="cferror_details">
    <li>Ray ID: 358c40410f9a0755</li>
    <li>Your IP address: 85.17.15.64</li>
    <li>Error reference number: 502</li>
    <li>Cloudflare Location: Amsterdam</li>`

**Comment by jtormey** [comment]
Strange that this is only an issue with a single wallet. Are you able to create a new wallet, and access that through the API?

**Comment by tinodj** [comment]
Hi,

I haven't tried creating new wallet. But my other wallet created earlier works. Actually it was giving wrong password for some time, but then after I restarted the service it started working. My first wallet still having issues, and it is also having issued when opening through web. Very slowly shows balance and transactions (sometimes it takes 30mins to show them, sometimes it does not show at all).

**Comment by tinodj** [comment]
I will close this one - now it seems all good again.
