### ISSUE TITLE
Not able to send a transaction

### ISSUE THREAD

**Issue by b12k** [blockchain/service-my-wallet-v3#246]
Wallet v0.26.0
Node 8.1.4

Greetings, 
I'm facing a problem with sending btc via service-my-wallet-v3.
Everything was working OK before 15.07.2017 and then it suddenly stopped working (no changes were made).

Service runs on Heroku.
It is called from PHP client.
I'm using two passwords.
All Heroku IP's are whitelisted.

![console output](https://image.prntscr.com/image/68E_b7ZLSxWD8I4QPpIgtg.png)

What can it be and what does ```error: [object Object]``` mean?

Thank you in advance!

**Comment by b12k** [comment]
I think this is some how related with ```Second password required to prepare KV Store```

Can some body help me with an issue?
Otherwise I need to switch to a different wallet provider... =(

**Comment by b12k** [comment]
Here some additional logs.
Wallet service doesnt work locally as well.
```bash
1500675185755 - info: blockchain.info wallet service v0.26.0 running on http://127.0.0.1:3000
Second password required to prepare KV Store
{ error:
   { AssertionError [ERR_ASSERTION]: [object Object]
       at new Transaction (C:\code\bcws\node_modules\blockchain-wallet-client\lib\transaction.js:45:3)
       at Payment.<anonymous> (C:\code\bcws\node_modules\blockchain-wallet-client\lib\payment.js:413:29)
       at <anonymous>
       at process._tickCallback (internal/process/next_tick.js:188:7)
     generatedMessage: false,
     name: 'AssertionError [ERR_ASSERTION]',
     code: 'ERR_ASSERTION',
     actual: false,
     expected: true,
     operator: '==' },
  payment:
   { fees: { priority: 220, regular: 30, limits: [Object] },
     coins: [],
     selectedCoins: [],
     from: [],
     amounts: [ 50000 ],
     to: [ 'HERE_GOES_WALLET_ID' ],
     feePerKb: 30000,
     extraFeeConsumption: 0,
     sweepFee: 0,
     sweepAmount: 0,
     balance: 0,
     finalFee: 0,
     changeAmount: 0,
     maxFees: { priority: 0, regular: 0, limits: NaN },
     maxSpendableAmounts: { priority: 0, regular: 0, limits: NaN },
     txSize: 0,
     blockchainFee: 0,
     blockchainAddress: null,
     serviceChargeOptions: {},
     change: undefined,
     wifKeys: [],
     fromAccountIdx: null,
     fromWatchOnly: false } }
1500675194318 - error: [object Object]
```

**Comment by jtormey** [comment]
Hey! Sorry for the delay, wasn't able to get to this over the last week unfortunately. The additional logs are helpful, I'll look closer at the issue later today. Thanks for your patience.

**Comment by jtormey** [comment]
I haven't been able to reproduce this yet (even with second password + seeing KV store warning), but it looks like the assertion thrown because there aren't any `coins` to spend. The `from` array is empty, which would explain why there aren't any coins. I'm not sure why `from` is empty though, are you specifying an account index / address?

**Comment by b12k** [comment]
@jtormey Hmmm. No I do not specify "from".
I do request as following:
```php
$response = $Blockchain->Wallet->sendMany($recipients, null, $computedFee);
```
According to [PHP Wallet Doc](https://github.com/blockchain/api-v1-client-php/blob/master/docs/wallet.md#send) `from` is optional.
We do not use multiple wallets - so I assume it should take the default one.

**Comment by binita49** [comment]
My transactions  not  working on

**Comment by BitEx21** [comment]
@b12k did you manage to get it working ? if so please post solution

**Comment by yoryi** [comment]
alguien puede ayudarme subi mi servcio a heroku pero obtengo errores. 

![Captura de Pantalla 2020-07-15 a la(s) 10 37 40 p  m](https://user-images.githubusercontent.com/16271026/87629096-ea660e00-c6f7-11ea-9d71-81a952595106.png)
