### ISSUE TITLE
20 address gap limitation？

### ISSUE THREAD

**Issue by koalsky** [blockchain/service-my-wallet-v3#265]
##This sentence means: xpub generated 20 btc address, if the 20 addresses are not used, then more than the limit, will not be generated?
@tuzzolo @colkito @zootreeves @hiraedd @axelay @jtormey

**Comment by jtormey** [comment]
That's correct, we do not generate more than 20 unused addresses in a row, which complies with the BIP 44 spec: https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#address-gap-limit

**Comment by koalsky** [comment]
Thank you @jtormey
