### ISSUE TITLE
Operation Logic

### ISSUE THREAD

**Issue by BizSafe** [blockchain/service-my-wallet-v3#274]
blockchain-wallet-service -V
0.26.0

Hi,
I am new to blockchain and trying to understand the logic
I need to create and manage a number of wallets for different individuals so use

http://localhost:3232/api/v2/create to create the said wallets

I then upgrade them to HD using

http://localhost:3232/merchant/'|| p_guid || '/enableHD

Next step (I think) is to create an account that will be used for the payments between these wallets

I try 
http://localhost:3232/api/v2/merchant/' || p_guid || '/accounts/create/
this seems to be creating a whole new wallet as I get a 
"warning":"Created non-HD wallet, for privacy and security, it is recommended that new wallets are created with hd=true"}

Is an account another wallet inside a parent?  Where can I find a document that explains all these concepts?

Thank you

**Comment by jtormey** [comment]
The proper create account endpoint is `http://localhost:3232/merchant/:guid/accounts/create/`, try using that and please let me know if it works. I think what is happening is that you are using the v2 API, and the `/accounts/create` part of the request is matching with the `/v2/create` route... I'll look into that.

As far as how the overall system works, you create a single parent "wallet", which contains any number of child "accounts" (and are unrelated except that they share a parent) that are used to store / send / receive bitcoin. It follows the BIP44 spec, which you can read [here](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki).

**Comment by BizSafe** [comment]
Thank you for the swift response.  I will try deleting the wallet I created using /v2/create and start over usinf /account/create
I'm away today but will feed back once I have given it a go

**Comment by BizSafe** [comment]
Hi again,

The thing that confuses me is if I remove the wallet I created using api/v2/create/ then what guid do I use for /merchant/:guid/accounts/create

What am I missing :)

**Comment by jtormey** [comment]
Hi, the guid is returned in the response to `/v2/create`, save that and use it in future API calls.

**Comment by BizSafe** [comment]
Thank you

**Comment by devsahamerlin** [comment]
you can just add params as "hd":true in your post request
