### ISSUE TITLE
Start service automatically

### ISSUE THREAD

**Issue by ijazpk** [blockchain/service-my-wallet-v3#286]
$ sudo blockchain-wallet-service start --port 3000
It will start local service, but I can not find - how to run it forever...Some ideas?

Please help

*Service 0.26.0,Node v7.10.1
*

**Comment by tva10** [comment]
May be simple solution is creating `.bat`/`.sh` file with start command and adding that script into autostart.

But it is possible to create `init.d` script. I saw an example in project wiki: [Upstart Integration](https://github.com/blockchain/service-my-wallet-v3/wiki/Upstart)

**Comment by ijazpk** [comment]
Thank you tva10

**Comment by banarsiamin** [comment]
not undastent please explen
