### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Ravskiy** [blockchain/service-my-wallet-v3#29]
I'have error during installation:

ubuntu 14.04 with latest updates.

root@b:/# npm -v
3.6.0
root@b:/# node -v
v0.12.9
root@b:/# npm install -g blockchain-wallet-service
/usr/bin/blockchain-wallet-service -> /usr/lib/node_modules/blockchain-wallet-service/bin/cli.js
/usr/lib
└─┬ blockchain-wallet-service@0.14.0 
├─┬ body-parser@1.14.2
│ └── type-is@1.6.11 
└─┬ request-promise@1.0.2
├── UNMET PEER DEPENDENCY continuation-local-storage@~3
└─┬ request@2.69.0
├─┬ har-validator@2.0.6
│ └─┬ pinkie-promise@2.0.0
│ └── pinkie@2.0.3 
└── oauth-sign@0.8.1

npm WARN cls-bluebird@1.0.1 requires a peer of continuation-local-storage@~3 but none was installed.
root@b:/#

Can you advice, how to fix the issue?

**Comment by jtormey** [comment]
npm 3 changed the way peer dependencies are handled. To get the correct install, try downgrading to npm 2: `npm install -g npm@2`, and then retry the install.

**Comment by Ravskiy** [comment]
Thank you a lot! After I have downgraded npm to v2 it was installed successfully.

**Comment by jtormey** [comment]
Great!
