### ISSUE TITLE
Get Address from HD Wallet and set callback URL

### ISSUE THREAD

**Issue by PriyanshDwivedi** [blockchain/service-my-wallet-v3#291]
Service v0.26.0, Node v6.10.3

Right now, I am following the following sequence to provide unique addresses to all my customers.
1. Create New HD Account
2. Use `Generating a Receiving Address [GET]` API from `Receive Payment API v2` to generate the address and also set the callback URL while generation
3. Share the generated address with my customer and update their wallet balance in my system whenever payment is received.

This was working fine, but now I am facing issues when payment is received on these addresses and the callbacks are getting mixed up somehow and there's no way to check what callback is set to which address. Also, the generated addresses don't show up in my blockchain.info wallet's settings section.

I was thinking about the following sequence to implement.
1. Create New HD Account
2. Get HD Account Receiving Address
3. Use `Balance Updates [POST]` API from `Receive Payment API v2` to set my server's callback URL for the address received from step 2

Will this be the correct approach?

**Comment by jtormey** [comment]
The receive payments API lets you add extra parameters to the callback url. So something you can do is to add a unique id ("payment id"?) to each callback url. Then, when the callback is called, you inspect the payment id to know which payment the callback is associated with. Does that sound like it would help solve your issue?

**Comment by PriyanshDwivedi** [comment]
@jtormey, thanks for your response. Yes, I have already added user's phone number as an extra parameter in the callback url to check which user's wallet needs to be updated.
I found the issue that was making the callbacks mixed up though. Thanks for your help. You can close this one.

**Comment by jtormey** [comment]
Glad you were able to solve the issue!

Although, I'd recommend not sending sensitive information (like phone numbers) through the API for payment tracking. It would be better to generate a random identifier for each payment and check for it when the callback url is called.
