### ISSUE TITLE
Receive Payment API v2 not working anymore

### ISSUE THREAD

**Issue by ConKreter** [blockchain/service-my-wallet-v3#293]
I know this is not the right place to ask, but I already wrote a support ticket which is not bringing me anywhere.
Basicly the Receive Payment API v2 can still create new addresses and we also get callback confirmation 0. But we dont get further callbacks. I have transactions with far more over 100 confirmations but we only got confirmation 0. 
Is it a general problem in the blockchain.info service? Could it be that our api key got blocked (we can still create more addresses with our xpub via the API and we also get callback 0)? Maybe our domain got someone blocked due to frequent amount of transactions?

Help would be highly appreciated.
Kind Regards
Adrian

**Comment by munkh-erdene** [comment]
Same in here. Please help us.

**Comment by ConKreter** [comment]
fixed again
