### ISSUE TITLE
There is no response at startup

### ISSUE THREAD

**Issue by zhaoqk** [blockchain/service-my-wallet-v3#297]
Hi
Thank you for checking my problem.
Here are the details of my problem

Node v6.3.0*,npm v3.10.3 ,linux x64

[root@iZm5e16hb28yj60w usr]# blockchain-wallet-service start -p 8899
1510884136594 - info: blockchain.info wallet service v0.26.0 running on http://127.0.0.1:8899
After executing the above command,There has been no response

**Comment by jtormey** [comment]
Do you mean that none of the api endpoints are working for you?

**Comment by zhaoqk** [comment]
Thank you very much for looking at my problem. This problem has been solved.
