### ISSUE TITLE
http://localhost:3000/api/v2/create

### ISSUE THREAD

**Issue by JnTxxxY** [blockchain/service-my-wallet-v3#301]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*

**Comment by jtormey** [comment]
Please include a description when opening Github issues.

**Comment by rgbetanco** [comment]
blockchain-wallet-service version 0.26.1
nodejs version v8.11.2

php code

$url = "http://localhost:3001/api/v2/create";
	 $a = "password=123ascdefrvgtt2133ewdddweyyhhhg&api_code=bb795b17-5d4c-415d-8887-e522923dda97";
	 $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $a);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 60);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    $ext_response = curl_exec($ch);
    curl_close($ch);
  return $ext_response'

The error that I get on the service is the following

warn: Created non-HD wallet, for privacy and security, it is recommended that new wallets are created with hd=true

and the return to the API is empty.

What am I doing wrong ? thanks

**Comment by GodBlock** [comment]
update the wallet to HD with http://localhost:3000/merchant/:guid/enableHD?.........
