### ISSUE TITLE
/merchant/:guid/list returned empty list for alpha wallet

### ISSUE THREAD

**Issue by dlimkin** [blockchain/service-my-wallet-v3#33]
Request: /merchant/:guid/list for alpha wallet
Response: { "addresses": [] }

Another question: 
Parametr "confirmations" is supported? There is documentation on blockchain, but not on github.

**Comment by jtormey** [comment]
To list out your HD accounts in the alpha wallet, use `/merchant/:guid/accounts`. The endpoint `/merchant/:guid/list` is only for individual imported addresses. Click [here](https://github.com/blockchain/service-my-wallet-v3#enable-hd-functionality) to go to the HD API docs.

To answer your second question, unfortunately the confirmations parameter is not supported as of right now.
