### ISSUE TITLE
Wallet Data Too Large

### ISSUE THREAD

**Issue by luoshushua** [blockchain/service-my-wallet-v3#335]
when I Generating a new address with api "http://localhost:3000/merchant/$guid/new_address?password=$main_password&second_password=$second_password&label=$label", response like this " {"error":"Unexpected error, please try again"} "， and an error “1520603116949 - error: Wallet Data Too Large”emerged at the console of the wallet service.

**Comment by jtormey** [comment]
This happens when your wallet payload has grown larger than the allowed limit. To fix this, you can export/delete addresses that you're not using anymore. Or create a new wallet and transfer your funds there.

**Comment by DigitalCoinsPH** [comment]
does this mean there is limit on creating new address? what is the limit of address we can generate using the api?

**Comment by luoshushua** [comment]
I get it  ,thank you for your help! @jtormey

**Comment by jtormey** [comment]
@DigitalCoinsPH the size of your wallet when stringified and encrypted can't be larger than 1MB. Note that only addresses generated with the `new_address` API will increase the size of your wallet, if you generate addresses using the accounts API the wallet will stay the same size.

**Comment by aahadr** [comment]
i got same problem,.. :(
