### ISSUE TITLE
Can't install the service

### ISSUE THREAD

**Issue by mehdibo** [blockchain/service-my-wallet-v3#336]
OS: Ubuntu 16.04
NodeJS: V8.10.0
NPM: 5.6.0

When I run `sudo npm install -g blockchain-wallet-service` I get the following result:

> npm WARN deprecated babel-preset-es2015@6.16.0: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
> npm WARN deprecated es5class@2.3.1: this package isn't maintained anymore because ES6+
> /home/mehdi/.npm_modules/bin/blockchain-wallet-service -> /home/mehdi/.npm_modules/lib/node_modules/blockchain-wallet-service/bin/cli.js
> + blockchain-wallet-service@0.26.0
> updated 1 package in 28.496s
> mehdi@mehdi-Laptop:~$ sudo npm install -g --no-optional blockchain-wallet-service
> npm WARN deprecated babel-preset-es2015@6.16.0: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
> npm WARN deprecated es5class@2.3.1: this package isn't maintained anymore because ES6+
> /home/mehdi/.npm_modules/bin/blockchain-wallet-service -> /home/mehdi/.npm_modules/lib/node_modules/blockchain-wallet-service/bin/cli.js
> + blockchain-wallet-service@0.26.0
> removed 12 packages and updated 1 package in 18.527s

After that I run `blockchain-wallet-service -v` I get:

> blockchain-wallet-service: command not found

**Comment by rashmitaparia** [comment]
getting same errors

**Comment by mehdibo** [comment]
I solved it by installing NodeJS V6
