### ISSUE TITLE
Watch only

### ISSUE THREAD

**Issue by stevesimba** [blockchain/service-my-wallet-v3#343]
Please I lost all my private keys in my imported wallets as I lost my phone. Now I have all my wallets back but without private keys so how can I get all my keys back. Please help me out because I can’t afford to lose all this money I have in my account.service-my-wallet-v3 and NodeJS version numbers when submitting an issue.

**Comment by jtormey** [comment]
Unfortunately, imported private keys cannot be recovered from a lost wallet. We strongly recommend using wallet HD accounts to avoid this issue.
