### ISSUE TITLE
Work with other coins like Ether or BTC Cash from api

### ISSUE THREAD

**Issue by teror4uks** [blockchain/service-my-wallet-v3#344]
Hello, I want ask about do I have opportunity to work with other coins from this service? I mean coins which allow from account like Ether or BTC Cash.

**Comment by lawrencegs** [comment]
Hey @teror4uks - have u figure out how to access the balance of ETH & Bitcoin Cash using API?

**Comment by markgukov** [comment]
Also, is it possible to retrieve a wallet's ETH receive address using the API?

**Comment by jtormey** [comment]
This API is only for accessing the BTC part of your wallet, we do not have plans to add other currencies at the moment.
