### ISSUE TITLE
can I get my transactions from the API

### ISSUE THREAD

**Issue by npomfret** [blockchain/service-my-wallet-v3#349]
When I download my transactions from the website, the wallet address is missing from the data.  I can only see the address if I mouse over the "From: My Bitcoin Wallet" text on the website.  

Is this transaction data available from the API (along with the wallet address)?

**Comment by SAWLIN** [comment]
transaction btc

**Comment by anguianomaria** [comment]
can  i get  my transaction from MY Bitcoin WALLET

**Comment by jtormey** [comment]
You can use our [Blockchain Data API](https://blockchain.info/api/blockchain_api) to do this. Just fetch your addresses / xpubs and send them in a request to `/multiaddr` (documentation in link).

**Comment by anguianomaria** [comment]
0x75c3cdb7c8adOa5D06Fa37bA5bIABb02ccB43C
153ecpaVuBLzwZTWpofW8gx8AWqMxDSU45
1KIYTmdJTav3tuUAS3mEJJcdymSKaaHTQm
1C1AxNQoFka7Q4yNWA2zJ3TRed3h5KZ2sf
1JyMirjzojBMpaPwNWAvkLEEN2V3WJQw
1MzDUPvAoChk9XVx38pMF4kgA8GTEcrajx
mis direcciones  como las podria  mandar

**Comment by anguianomaria** [comment]
ok gracias
