### ISSUE TITLE
blockchain-wallet-service on azure

### ISSUE THREAD

**Issue by proBeejay141** [blockchain/service-my-wallet-v3#355]
Pls, how can i use blockchain-wallet-service on azure

**Comment by jtormey** [comment]
I haven't used Azure before, have you tried running it inside a Docker container?

**Comment by jtormey** [comment]
Sure, I don't see why not.

**Comment by ThanakonJakkam** [comment]
ต้องลอง

**Comment by proBeejay141** [comment]
i mean i will be able to run blockchain-wallet-service on localhost with
port 3000, on VM?

**Comment by proBeejay141** [comment]
okay. thanks

**Comment by anguianomaria** [comment]
okay thqnks

**Comment by anantanandgupta** [comment]
Here is the dockerized version of the latest build https://hub.docker.com/r/dockermgt/my-wallet-service

**Comment by ravikantcool2008** [comment]
Sorry this is not my flat. You asked the wallet owner.

R@v!1985

**Comment by ravikantcool2008** [comment]
I've added you to my whitelist on BitBounce!
[image: BitBounce]



Hello!

I’ve signed up for a cryptocurrency spam solution called BitBounce and I
added you to my “whitelist”. That means you can email me and your emails
will come through.

For people who aren’t on my whilelist, I’m charging $0.05 in Credo for
their email to get to my inbox. A cleaner inbox and more money? Win! You
should check it out!

*Sign up for BitBounce and earn 1 complimentary Credo.*
<https://bitbounce.com?ref=bitbounce>

Unsubscribe
<https://bitbounce.com/unsubscribe_from_whitelist_email_notifications/363724878>
from ravikantcool2008@gmail.com's whitelist notification emails.



*BitBounce* <https://bitbounce.com?ref=bitbounce> is powered by the *Credo*
<https://bitbounce.com/credo> cryptocurrency

*I’m from a business* —  what are my *delivery options*
<https://business.bitbounce.com>

BitBounce and Credo are transacted through *CredoEx*
<https://credoex.com?ref=bitbounce>
Made by Turing Technology Inc. in San Mateo, California *Sign Up for
BitBounce* <https://bitbounce.com?ref=bitbounce>

**Comment by ravikantcool2008** [comment]
0x0fd8fB6a383DCc783b227d99e7c93a54E6fDA9eF
