### ISSUE TITLE
blockchain/service-my-wuallet-v3

### ISSUE THREAD

**Issue by anguianomaria** [blockchain/service-my-wallet-v3#361]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*

**Comment by anguianomaria** [comment]
blockchain/service-my_wuallet-V3

**Comment by jtormey** [comment]
Please leave a detailed description when opening a Github issue, thanks!
