### ISSUE TITLE
ERR_TIMEOUT when trying to log in

### ISSUE THREAD

**Issue by joolswills** [blockchain/service-my-wallet-v3#37]
`blockchain-wallet-service start --port 3000 &`

blockchain.info wallet service v0.15.0 running on 127.0.0.1:3000

```
wget -O- "http://localhost:3000/merchant/MYGUID/login?password=MYPASSWORD&api_code=MYAPICODE"
```

returns

```
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... ERR_TIMEOUT
500 Internal Server Error
2016-02-17 11:19:36 ERROR 500: Internal Server Error.
```

running on Debian Wheezy with nodejs from backports (0.10.29~dfsg-1~bpo70+1)

**Comment by shawnblue** [comment]
I could not get it to run reliably on a pi. A or B It times out, does not
respond, sometimes works. It installs on a B and kind of runs but it's very
unstable. I ended up building a server in a VPC. With VPN, nginx https and
some port forwarding. Also if you want to keep it running I had great
success with supervisor.
On Wed, Feb 17, 2016 at 6:21 AM Jools Wills <notifications@github.com>
wrote:

> blockchain-wallet-service start --port 3000 &
>
> blockchain.info wallet service v0.15.0 running on 127.0.0.1:3000
>
> wget -O- "http://localhost:3000/merchant/MYGUID/login?password=MYPASSWORD&api_code=MYAPICODE"
>
> returns
>
> Resolving localhost (localhost)... 127.0.0.1, ::1
> Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
> HTTP request sent, awaiting response... ERR_TIMEOUT
> 500 Internal Server Error
> 2016-02-17 11:19:36 ERROR 500: Internal Server Error.
>
> running on Debian Wheezy with nodejs from backports
> (0.10.29~dfsg-1~bpo70+1)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blockchain/service-my-wallet-v3/issues/37>.
>
-- 
"The only way to deal with an unfree world is to become so absolutely free
that your very existence is an act of rebellion."
--Albert Camus

**Comment by joolswills** [comment]
I would add this is running on a x86_64 setup, so not related to rpi.

**Comment by shawnblue** [comment]
Sorry I read "wheezy" figured you were trying to run this on a pi sorry!
On Wed, Feb 17, 2016 at 8:10 AM Jools Wills <notifications@github.com>
wrote:

> I would add this is running on a x86_64 setup, so not related to rpi.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blockchain/service-my-wallet-v3/issues/37#issuecomment-185195858>
> .
>
-- 
"The only way to deal with an unfree world is to become so absolutely free
that your very existence is an act of rebellion."
--Albert Camus

**Comment by jtormey** [comment]
The minimum recommended nodejs version is v0.12.0. Versions before that lack needed methods, such as `Buffer.prototype.compare`.

**Comment by joolswills** [comment]
was this documented anywhere or did I miss it ?

**Comment by joolswills** [comment]
can confirm it is working now with a newer nodejs. thanks.

**Comment by jtormey** [comment]
The node version is listed in the package.json `engine` field, so npm should give a warning when installing with an unsupported version. I'll add it to the README as well though.
