### ISSUE TITLE
Make Payment does not work with all possible combinations

### ISSUE THREAD

**Issue by espriweb** [blockchain/service-my-wallet-v3#384]
Hi, I've tried all the service-my-wallet-v3 APIs and they work correctly, while only those to send Bitcoins do not work.

Below are the attempts I made:

- Use Blockchain API library (PHP, v1)
- Use Blockchain Wallet API V2
- curl in the command prompt
- Directly in the browser
- Adding all optional parameters (service-my-wallet-v3)
- With the "fee" parameter of 10000 satoshi
- With the "amount" parameter greater than 50000 satoshi
- second_password, api_code, from etc.

The result is always the same: 
- {"error": "Unexpected error, please try again"}
- 1541190919186 - error: [object Object]

http://localhost:3000/merchant/:guid/payment?to=1FsCCtH6ZjVadS1GJm84gLRoRKZy92Bh28&from=1McDbVSVLUkvrr2eUUbBdd2ETiFGxFReoi&amount=53405&password=xxxxxxxx&fee=10000

$response = $Blockchain->Wallet->send("1FsCCtH6ZjVadS1GJm84gLRoRKZy92Bh28", "0.00053405", null, "0.0001");

You can help me? Thanks in advance.

Service-my-wallet-v3 = v0.26.1
NodeJS = v10.13.0
Npm = v6.4.1

**Comment by espriweb** [comment]
RESOLVED,

in the "from" field you must enter the index of the wallet, which is retrieved with the following api command:

http://localhost:3000/merchant/guid:/accounts/xpubZZZZZZZZZZZZ?password=XXXXXXXX

Output:

{"balance":0000,"label":"BitcoinWallet","index":0,"archived":false,"extendedPublicKey":"xpubZZZZZZZZZ","extendedPrivateKey":"xprvZZZZZZZZZ","receiveIndex":3,"lastUsedReceiveIndex":2,"receiveAddress":"xxxxxxxxxx"}

**Comment by roydondsouza** [comment]
@espriweb thank you. This helped us move out the funds from each sub-wallet individually. We were also facing delays of up to 4 hours in callbacks from blockchain.info to our URLs during peak hours.
We dropped the integration with blockchain.info and moved to hosting our own full bitcoin node, since we couldn't move out our funds using this library for many days.

**Comment by espriweb** [comment]
> @espriweb thank you. This helped us move out the funds from each sub-wallet individually.
> 
> We were also facing delays of up to 4 hours in callbacks from blockchain.info to our URLs during peak hours.
> 
> We dropped the integration with blockchain.info and moved to hosting our own full bitcoin node, since we couldn't move out our funds using this library for many days #382 .
> 
> Did anyone face similar issues? I spoke to a few people I knew, and they had these issues, but customer support doesn't acknowledge this after providing logs.

Hi @roydondsouza ,

I'm happy to have been helpful, unfortunately I do not have much experience in this sector and with blockchain.com I'm still testing with the "API".

On my servers I downloaded a "full node" bitcoin, can you tell me a simple library to use and install that allows me to do the same things as the API of blochchain.com?

Thanks in advance!!

**Comment by GoldFund** [comment]
Let me know if you find a library for the "full node". I am looking at migrating to Coinsbase API now. I have too many users and scaleablity is a factor in this decision.

**Comment by roydondsouza** [comment]
@espriweb , @GoldFund we are doing the research. I will keep you updated. Our first candidate was https://github.com/bitcoinj/bitcoinj to be used with an independent [full node](https://bitcoin.org/en/full-node#what-is-a-full-node). But we are still looking into other things. Like a JSON-RPC library and build a wrapper around it.

**Comment by roydondsouza** [comment]
@GoldFund we went ahead with the bitcoin core RPC provided in the full node. We built our own layer around it for internal consumption. We are glad we moved out of @blockchain on time. We moved close to 1100 BTC so far through our systems in a short span of time.

**Comment by tharin567** [comment]
$response = $Blockchain->Wallet->send("1FsCCtH6ZjVadS1GJm84gLRoRKZy92Bh28", "0.00053405", null, "0.0001");

**Comment by naigueldev** [comment]
In my case I informed the index of the address but the error continued, so I was informing the value of 0.05 and I changed it to the minimum value 546 which is the equivalent of 0.00000546 BTC and then it worked.

`http://localhost:3000/merchant/:wallet_id/payment?password=xxxxxx&to=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&amount=546&from=0&fee=675`
