### ISSUE TITLE
Strange responce to balance call

### ISSUE THREAD

**Issue by Goldminerpool** [blockchain/service-my-wallet-v3#39]
Hi!
We managed to login to alpha wallet, using API key, we get a proper responce. After that, we were trying to get a balance of a alpha wallet, and we got an error answer, attached in .txt document. Is this a bug or are we doing something wrong?
Regards,
M.

[error-report.txt](https://github.com/blockchain/service-my-wallet-v3/files/136079/error-report.txt)

**Comment by jtormey** [comment]
Hi, what is your node version? The service requires >= 0.12.0. This error tends to occur when it is running on version 0.10.0 (the Buffer.prototype.compare method wasn't in node at that point).

**Comment by Goldminerpool** [comment]
Thank you, updating our node resolved the problem. 
Regards,
M.
