### ISSUE TITLE
no received  my money 

### ISSUE THREAD

**Issue by najeh22** [blockchain/service-my-wallet-v3#391]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*

**Comment by jtormey** [comment]
Please include a description of the problem you have when opening a Github issue. Thanks!

**Comment by najeh22** [comment]
I can't  transfer  money

**Comment by najeh22** [comment]
How  much  money  I have  in this  site
