### ISSUE TITLE
Problem sending to many - 20 recipients

### ISSUE THREAD

**Issue by leex** [blockchain/service-my-wallet-v3#40]
When I try to sendToMany recipients, I get an error like:

`Server error response [url] http://127.0.0.1....`

The service reports these errors:
`Transaction.prototype.sign is deprecated.  Use TransactionBuilder instead.
Transaction.prototype.signInput is deprecated.  Use TransactionBuilder instead.`

The error message cuts off after about the 15th recipient, I've tried with both GET and POST, putting the data as query parameters (is there some way I can put the recipients array in the POST body?).

I'm running it on port 3333 but that shouldn't matter.

**Comment by jtormey** [comment]
The `Transaction.prototype` warnings are harmless. Does the service respond with an error message? Without more information, it's hard for me to know exactly what's going on.

**Comment by leex** [comment]
Here is the exact output from the script, with some obfuscation:

`PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ServerException' with message 'Server error response [url] http://127.0.0.1:3333/merchant/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/sendmany?password=xxxxxxxxxxxx&second_password=xxxxxxxxxxxx&recipients=%7B%22156BdAgbD5yL5o7kEnzEnSHNeCfNWS6caC%22%3A2935913%2C%2218wpjx59jbg8GXgghmqDkHdBF6MJqXSfeK%22%3A7339782%2C%221ABfaz423shYuguzxjhU9JqWyE5KEue3JX%22%3A7339782%2C%221LZyEiyMuDPPSLNt1atth2GMc1kQU2huAN%22%3A14679564%2C%221NKUXfx131MmwYxmbte3zzYW6vN4Qn6ZwS%22%3A1467956%2C%221Hmjk1W5oiDwkqBZvvnPK1aMufgmBLjs4C%22%3A3669891%2C%221PsxhxE7BPVZ1s87ReCzx4HEA4pqvcMQki%22%3A1467956%2C%221EgrQ2rLPrDPSr17nRkSVjDWHF7y7uZ94s%22%3A2201935%2C%221CUUxgRnXVFDD4q2k2XrqaFTen1iYza9A9%22%3A1467956%2C%221KD36BK47mVJyMWauVbBFsyjNot93kdYMh%22%3A1467956%2C%2212gBiABjTeH4aE82p4EeVbxdhhV2S7B8X6%22%3A14679564%2C%2213f3agsHvua123KhXfzs81MacByAz2s2YL%22%3A1467956%2C%221AG9eCdddnMWJ2npd3M4htHNBo7aKPARiw%22%3A1467956%2C%2214zF7vFSx5a57gunc4H1FNaheJU3Y3J8Um%22%3A5871825%2C%221QCp4syXEtsEYaKijeBNKUf8YkNZyKK3z5% in /var/xxxx/xxxx/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 71`

This exact same request works using the normal API with file_get_contents. I cannot provide any more information sorry, there simply isn't any.

I could only recommend trying a similar request yourself, I would imagine it's part of a testing suite anyway?

**Comment by jtormey** [comment]
I tried several large "sendmany" transactions just now, and didn't have any issues (links to transactions below). Is it possible the request library you're using has some restriction?

20 recipients: https://blockchain.info/tx/4430ad164c51d7ab7aeec27553e18cbf5d4f14dd51a8fbd3eefa29b1c6dfb223
40 recipients: https://blockchain.info/tx/26689d41ec13e384be370d3b6e600b563b722228be1086f200b83882717d7eab
40 recipients: https://blockchain.info/tx/2b011f974360ca8bbec4c7277e95ef529f5eeb39dd650729d263778b99398fa0

**Comment by leex** [comment]
No it's not the client (guzzle). When I first started using the service I simply setup the login request and changed the route to http://127.0.0.1/, making all requests with file_get_contents. The login and balance requests worked fine but the sendMany didn't.

I am not sending the parameters in the post body but I will try that now.

**Comment by leex** [comment]
Okay I've tried with only one recipient and the parameters in the body like this:

https://gist.github.com/leex/5a99cbaab0ce18cff21f

I get this error from the service:

`Transaction.prototype.sign is deprecated.  Use TransactionBuilder instead.
Transaction.prototype.signInput is deprecated.  Use TransactionBuilder instead.
There is an output too small to publish a note
There is an output too small to publish a note`

The same request works to /balance with just the password parameter.

**Comment by jtormey** [comment]
Are you sending from an address with a small balance? That error happens when any of the transaction outputs are below 5460 satoshi, which includes change outputs.

**Comment by leex** [comment]
The address has single unspent output greater than 15000000 Satoshi.

**Comment by pernas** [comment]
The problem is that you cannot set a public note for if there is an small output. Where small is quite high to avoid spam. Don not set the public note.

**Comment by pernas** [comment]
Even your output is big, if the change is small counts as a small output

**Comment by jtormey** [comment]
Ah that's right, the limit for a public note isn't the dust limit, thanks @pernas. Hopefully this should be resolved now, sorry for all the trouble @leex. I [just added](https://github.com/blockchain/service-my-wallet-v3/commit/3803fc043797aa47b17d652a35c9ecae68492186) the 500000 satoshi rule to the docs so that this doesn't trip people up in the future.

**Comment by leex** [comment]
Thanks for your help, I removed the note and the transaction was broadcast.

I can't try it with multiple people yet until next week and I don't understand why the simple file_get_contents() get request with the recipients in the query string didn't work with the service when it works with the exact same tx through the http://blockchain.info/ endpoint but I will reopen if it doesn't work.

**Comment by jtormey** [comment]
There are certain limitations for the length of GET request urls. It's possible that these limitations are higher on blockchain.info. I'll look into this more tomorrow to see if I can do something about it.

**Comment by leex** [comment]
Reopening this issue because I've just tried to send the request to multiple people again using a note with output much bigger than 500000 and still had the internal error. When I removed the note however, it worked.

**Comment by pernas** [comment]
If any output is smaller than 500.000 it is going to fail. Even if it is the change.
