### ISSUE TITLE
Outgoing payment not working (2019)

### ISSUE THREAD

**Issue by Brayan233** [blockchain/service-my-wallet-v3#409]
Hello, i have some troubles with the outgoing payment with the API ( /merchant/:guid/payment ), it's always return "error":"Unexpected error, please try again"

I know there is many issues about this. I've tried every solutions (set all params even optionals one, set the "from" parameter with the wallet index etc) but still not working (see attachment)

The method is still working for you ? Thank's

![error1](https://user-images.githubusercontent.com/24452317/57714820-9dab2100-7675-11e9-8ebc-9629caa6818b.PNG)
![error2](https://user-images.githubusercontent.com/24452317/57714830-a26fd500-7675-11e9-9768-e0c238b24693.PNG)

Config: *service v0.26.3, Node v9.8.0*

**Comment by aminmazi** [comment]
same issue for me

**Comment by iScripters** [comment]
Same here

**Comment by Woojie** [comment]
For me, this was because my node version was too high. If you go to node 6.17.1 it should work (albiet throw an error in console about not using the keyword 'new') and if you go back to 6.4.1 it should work as intended. I'm wondering if there is a solution that doesn't involve rolling back node.

**Comment by Brayan233** [comment]
> For me, this was because my node version was too high. If you go to node 6.17.1 it should work (albiet throw an error in console about not using the keyword 'new') and if you go back to 6.4.1 it should work as intended. I'm wondering if there is a solution that doesn't involve rolling back node.

Thank's @Woojie , downgrade my node JS version worked for me.

**Comment by kennyendowed** [comment]
trying to send bitcoin to another address

am geting a error
$wallet = Blockchain::makeOutgoingPayment($wallet_guid, $amount, $wallet_password, $to_guid,$from_guid);

errors

file_get_contents(http://127.0.0.1:3000/merchant/ijfia83405-2339-fdjofe-b8d2-ergrgwgefa?payment?password=huyut7342s%4011&amp;api_code=8698dr4w5d-yftdt-lhilj-a7878-hisrwserwrt536&amp;to=1ABYVpfwSxPukqvmPDtZ6KiybgzRe4KaFF&amp;amount=10000.00000000&amp;from=1LMdnxXsuHuZaDeiqRMAkQfUc7JgdwsKVu&amp;fee=1000): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error\r\n in /var/www/html/coin_api/vendor/botdigit/blockchain/src/Blockchain.php:264

on d wallet server i get this
1593571032038 - info: blockchain.info wallet service v0.26.3 running on http://127.0.0.1:3000
1593571039821 - error: [object Object]
1593571117816 - error: [object Object]
1593571189722 - error: [object Object]
1593571618354 - error: [object Object]
1593572101402 - error: [object Object]

and i dont want to downgrade my node pls
