### ISSUE TITLE
Does not work option "confirmations"

### ISSUE THREAD

**Issue by Lanskih90** [blockchain/service-my-wallet-v3#42]
Hi,
Does not work option "**confirmations**" in the method **"/merchant/:guid/address_balance"**.
I write 3 confirm this method, He return the transaction with 0 confirmations!
Can fix it?

**Comment by jtormey** [comment]
There is a [note in the documentation](https://github.com/blockchain/service-my-wallet-v3#fetch-address-balance) mentioning that the confirmations parameter is not supported.

**Comment by Lanskih90** [comment]
Ok, How do I check confirmation in the transaction ?

**Comment by jtormey** [comment]
You can use our [Blockchain Query API](https://blockchain.info/q).

For example, to look up the balance of an address that has been confirmed with X confirmations:
https://blockchain.info/q/addressbalance/ADDRESS?confirmations=X

Hope that helps!

**Comment by Lanskih90** [comment]
Thanks!

**Comment by Lanskih90** [comment]
Hi,
I have in debug mode when I sent money an error is displayed 
> Server Time offset 61.3515625ms - This offset 62
Transaction.prototype.sign is deprecated.  Use TransactionBuilder instead.
Transaction.prototype.signInput is deprecated.  Use TransactionBuilder instead.
published
Server Time offset 61.67578125ms - This offset 62

but money sent!
My version 0.15.0

**Comment by jtormey** [comment]
Hi, thanks for reaching out. Those log messages are actually just warnings coming from a dependency of ours. They're not errors, which is why the service should still run smoothly. It's safe to ignore them, and in the meantime I'll look into removing them.

**Comment by Lanskih90** [comment]
Thanks!
