### ISSUE TITLE
documentation lacks "GET" and "POST" labels

### ISSUE THREAD

**Issue by internaught** [blockchain/service-my-wallet-v3#45]
[https://github.com/blockchain/service-my-wallet-v3#logging-into-a-wallet](Logging into a wallet) doesn't tell you if it's a GET or POST request. It only states that "parameters" should be passed. I'm guessing it's a POST request and the parameters being passed are the "data", right?

**Comment by jtormey** [comment]
It can be either a GET request with query parameters, or a POST with parameters in the POST body and sent with the `application/json` content-type header. I'll add that to the documentation, thanks for bringing it up!

**Comment by jtormey** [comment]
In the README
