### ISSUE TITLE
cannot create_wallet, please tell me what i am doing wrong

### ISSUE THREAD

**Issue by SilentHG** [blockchain/service-my-wallet-v3#457]
from blockchain import createwallet

wallet = createwallet.create_wallet('1234password', 'my_api_code_here', 'http://localhost:3000/', label = 'Test wallet')

print(wallet)

my npm promting this

1587226876270 - info: blockchain.info wallet service v0.26.3 running on http://127.0.0.1:3000
1587226879837 - error: Missing query parameter: password
1587227383717 - warn: Created non-HD wallet, for privacy and security, it is recommended that new wallets are created with hd=true
1587227400652 - warn: Created non-HD wallet, for privacy and security, it is recommended that new wallets are created with hd=true
1587227431823 - warn: Created non-HD wallet, for privacy and security, it is recommended that new wallets are created with hd=true

Service v0.26.3, Node v12.16.1*

I need the Json response of 
GUID, Address and Label.

Thank you,

**Comment by SilentHG** [comment]
nevermind it was to use

print(wallet.identifier)
print(wallet.address)

print(wallet.label)

**Comment by mariosanchezgarcia** [comment]
Hols
