### ISSUE TITLE
Unexpected error, please try again

### ISSUE THREAD

**Issue by arif7576** [blockchain/service-my-wallet-v3#458]
I want a solution below error.. please help me.
$url = "http://localhost:3030/merchant/$guid/payment?password=$main_password&to=$address&amount=$amount";

$ch = curl_init();
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($ch, CURLOPT_URL, $url);
		$ccc = curl_exec($ch);
		$json= json_decode($ccc, true);
		
		echo "<pre>";
		var_dump($json);

			echo "</pre>";

array(1) {
  ["error"]=>
  string(34) "Unexpected error, please try again"
}
![image](https://user-images.githubusercontent.com/62902326/79936893-6561b480-847a-11ea-84d8-ace59156012c.png)

**Comment by alexanderpavlovru** [comment]
You must define the param "from=0". It is an index of address in your wallet.
And make sure you set amount in satoshi.

**Comment by arif7576** [comment]
Thanks it's working
