### ISSUE TITLE
How to Start blockchain server in Windows

### ISSUE THREAD

**Issue by deepak-arora** [blockchain/service-my-wallet-v3#46]
I am trying to start blockchain-wallet-service in windows machine. Please let me know where I can run command blockchain-wallet-service start --port 3000 in window ?? On Command prompt this command is not working. plz help

**Comment by jtormey** [comment]
Did you install with [npm](https://npmjs.org), using the `-g` flag? If installed correctly, `blockchain-wallet-service` should be available as a command in the command prompt window.
