### ISSUE TITLE
Timeout when second login is requested

### ISSUE THREAD

**Issue by robsonhortela** [blockchain/service-my-wallet-v3#47]
Hello,

I have installed and started the service successfully. After start, when I send a login request (/merchant/:guid/login) its works fine. But if I send a new login request for a other guid, not works, after a time the service returns a timeout error:
{"error":"Call to /login timed out, please try again"}

and in the command prompt appears "ERR_TIMEOUT"

Can anyone help me?

**Comment by robsonhortela** [comment]
Obs: I tested with two OS, Win 7 e Windows Server 2008, both with the same issue.

**Comment by jtormey** [comment]
What version of the service are you running? Does the second wallet you're logging into have any additional security features, such as 2FA or email authorization?

**Comment by jtormey** [comment]
It's no longer necessary to call /login, and the timeout mechanism has since been improved to handle many concurrent wallets. Closing.
