### ISSUE TITLE
Feature request: Allow user to configure outbound HTTP proxy ip/port

### ISSUE THREAD

**Issue by kristovatlas** [blockchain/service-my-wallet-v3#5]

**Comment by jtormey** [comment]
Closed by PR #9

**Comment by mjm77** [comment]
Please unsubscribe mjm77@psu.edu from this email chain

On Wednesday, December 30, 2015, Justin Tormey <notifications@github.com>
wrote:

> Closed #5 <https://github.com/blockchain/service-my-wallet-v3/issues/5>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blockchain/service-my-wallet-v3/issues/5#event-502805549>
> .
>


-- 
Sincerely,



Michael J. Morelli
Information Services, Learning Assistant.
Mount Nittany Health, Pennsylvania State University
mjm77@psu.edu
mike.morelli@mountnittany.org
Mobile 814.769.3971
