### ISSUE TITLE
Misleading documentation / inconsistency with API v1

### ISSUE THREAD

**Issue by Informatic** [blockchain/service-my-wallet-v3#50]
Your [wallet API v1 docs page](https://blockchain.info/api/blockchain_wallet_api) (which you actually refer to in README) suggests that this service is a drop-in replacement for backwards compatiblity. In reality - `sendmany` endpoint returns completely different JSON object than API v1 (`txid` vs `tx_hash`, `success` boolean instead of `message`) making previous API clients unusable.

**Comment by jtormey** [comment]
Thanks for pointing that out! I [just added](https://github.com/blockchain/service-my-wallet-v3/commit/d602ac6e9c9b2e36f9da10c66246dc1133181a28) the missing properties, so from v0.17.2 forward there shouldn't be compatibility issues. Feel free to let me know if you see any other discrepancies.
