### ISSUE TITLE
Ubuntu server requires nodejs symlink after install

### ISSUE THREAD

**Issue by nebaughman** [blockchain/service-my-wallet-v3#51]
**Problem:** In Ubuntu server 14.04, `sudo apt-get install nodejs` installs the executable as `/usr/bin/nodejs`. Running `blockchain-wallet-service start --port 3000` results in `/usr/bin/env: node: No such file or directory` (it expects the executable to be `/usr/bin/node`).

**Fix:** After installing nodejs, create this symlink: `sudo ln -s /usr/bin/nodejs /usr/bin/node` and the wallet service can start as expected.

Please add this step to the installation instructions (or make sure the nodejs executable can be found at `/usr/bin/nodejs` on Ubuntu).

**Comment by nebaughman** [comment]
Similar to #52 - When installing nodejs/npm via NVM (within non-root user account), nodejs is installed local to the user's home dir & NVM sets up the environment to execute the node module locally. No `/usr/bin` symlink needed. Also no need to run nodejs as root!

**Comment by satellite1** [comment]
@nebaughman "When installing nodejs/npm via NVM (within non-root user account)" Did you assign this user to any particular group? Did you have Sudo during the install? I have another install that was successful but running and starting the service with root :/ Thanks!

**Comment by nebaughman** [comment]
@satellite1 I did not assign any particular group. I did not use sudo to run nvm. nvm installed nodejs & npm within the user's home (under `/home/user/.nvm/...`). The full path to the blockchain-wallet-service is: `/home/user/.nvm/versions/node/v0.12.10/bin/blockchain-wallet-service`. The service can also run non-root (non-sudo).
