### ISSUE TITLE
Timeout when connecting to  to Wallet Service

### ISSUE THREAD

**Issue by rmcdermott** [blockchain/service-my-wallet-v3#53]
I am running the service on Debian Jessie. and Node v5.7.0

I have tried connecting via wget and via file_get_contents.   Both methods time out.

wget outputs: 
Connecting to localhost (localhost)|::1|:3000... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2016-02-28 07:11:44 ERROR 500: Internal Server Error.

Node console outputs:
ERR_TIMEOUT

It seems unrelated to the other tickets with the same issue as my node version is up to date.

**Comment by RichAyotte** [comment]
I'm seeing the same problem. Connection refused on all attempts. The last working version was 17.2 so it looks like the login deprecation changes caused a regression.

**Comment by RichAyotte** [comment]
I got it working. `sudo npm update -g blockchain-wallet-service` will not properly install the new version so yo need to `sudo npm uninstall -g blockchain-wallet-service` followed by `sudo npm install -g blockchain-wallet-service` Tested with v5.7.0 and npm 3.8.0

**Comment by jtormey** [comment]
@RichAyotte thanks for letting me know, it might be because caused by dependencies that were added. I'll keep looking into why that may have happened.

**Comment by jtormey** [comment]
No longer an issue as of v19.2

**Comment by bilawalali512** [comment]
How to resolve this issue on Cpanel. i am using laravel
