### ISSUE TITLE
iOS mobile wallet not accessible

### ISSUE THREAD

**Issue by captJiri** [blockchain/service-my-wallet-v3#541]
Hi, cannot get in to my blockchain wallet on my iPhone. After i give both passwords the app gets not in, only cycling...
Thanks.

**Comment by NVidanovic** [comment]
Me too.
The message is Upgrading wallet to v4. Please do
not close the app.

**Comment by captJiri** [comment]
My ver. is v5.1.0 - not possible to get in the wallet on iphone iOS - cycling for ever on the blue log-in screen after i add the 2nd password.

**Comment by NVidanovic** [comment]
Now, I have the same behavior as you. The version is the same v5.1.0

**Comment by Yommyjay222** [comment]
> My ver. is v5.1.0 - not possible to get in the wallet on iphone iOS - cycling for ever on the blue log-in screen after i add the 2nd password.

Do you have your 12 recovery phrase?

**Comment by Yommyjay222** [comment]
Let me know if you do

**Comment by captJiri** [comment]
HOW TO SOLVE MOBILE WALLET LOG-IN ISSUE:
Log-in in PC browser/go security and turn-off "the 2nd password", also turn-off "the 2FAauth.". Then set-up new 2FA auth./set-up google auth. or your mobile device. Delete the mobile app with all data and re-install it in your mobile + log-in with new security set-up made in your PC browser.

**Comment by captJiri** [comment]
> Hi, cannot get in to my blockchain wallet on my iPhone. After i give both passwords the app gets not in, only cycling...
> Thanks.

Solution down bellow.

**Comment by johnjames333** [comment]
we have developed our own hardware for cracking all versions of blockchain wallet password with superfast speed
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333 or gmail : walletsrecoveryservice@gmail.com
