### ISSUE TITLE
ERR_TIMEOUT when trying access localhost:3000

### ISSUE THREAD

**Issue by ladhitya** [blockchain/service-my-wallet-v3#60]
Hi there, I seems to have an issue with blockchain installation on a specific server.
on command wgte -O- 'http://localhost:3000/merchant/<guid>/login?password=<psw>&second_password=&api_code=<api_code>' -S

my server is Ubuntu 14.10, using Node v5.6.0, service wallet Service v0.18.1

I always gets the ERR_TIMEOUT on login.

> Resolving localhost (localhost)... 127.0.0.1
> Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
> HTTP request sent, awaiting response...
>   HTTP/1.1 500 Internal Server Error
>   X-Powered-By: Express
>   Content-Type: application/json; charset=utf-8
>   Content-Length: 54
>   ETag: W/"36-v7XDKMlQr2iDBgxMVphxsQ"
>   Date: Thu, 03 Mar 2016 06:31:54 GMT
>   Connection: keep-alive
> 2016-03-03 17:31:54 ERROR 500: Internal Server Error.

using curl will result the following:

> Hostname was NOT found in DNS cache
>   Trying 127.0.0.1...
> Connected to localhost (127.0.0.1) port 3000 (#0)
>  GET /merchant/<guid>/login?password=<psw>&api_code=<api_code> HTTP/1.1
>  User-Agent: curl/7.37.1
>  Host: localhost:3000
>  Accept: */*
> 
>  HTTP/1.1 500 Internal Server Error
>  X-Powered-By: Express
>  Content-Type: application/json; charset=utf-8
>  Content-Length: 210
>  ETag: W/"d2-V9XisWlAb+M1EPq/DirdsA"
>  Date: Thu, 03 Mar 2016 06:48:04 GMT
>  Connection: keep-alive
> 
>  Connection #0 to host localhost left intact
> {"error":"Wallets that require email authorization are currently not supported in the Wallet API. Please disable this in your wallet settings, or add the IP address of this server to your wallet IP whitelist."}

is there something I missed ? 

Cheers

**Comment by jtormey** [comment]
Does this happen to every wallet you try to use? The error message in the curl output says that it couldn't get the wallet because the wallet is protected with email authorization.

**Comment by ladhitya** [comment]
I havent tried with another wallet, however when I tried it on 2 other different servers, it works fine using the same wallet. 
any ideas ? or have you come across something like this ?

**Comment by ladhitya** [comment]
Nvm guys, its a stupid mistake on my part. after I update the api wget showed the error to whitelist ip address. after I added the server's ip address to that whitelist, everything worked!

thank you! :+1:
