### ISSUE TITLE
Document service upgrade process

### ISSUE THREAD

**Issue by nebaughman** [blockchain/service-my-wallet-v3#61]
*Service v0.17.2, Node v0.12.10*

Please document the process to safely upgrade the service to the latest version (e.g., via npm). Are there production vs. development releases?

**Comment by jtormey** [comment]
Upgrading to the latest version should just require `npm update -g blockchain-wallet-service`. I'll add that to the installation section of the docs.

Releases that follow standard [semver](http://semver.org/) format are considered safe to use. Development releases are postfixed with `-dev` and should not be used in production.
