### ISSUE TITLE
Add timestamps to log output

### ISSUE THREAD

**Issue by nebaughman** [blockchain/service-my-wallet-v3#68]
*Service v0.17.2, Node v0.12.10*

Debug/log output from the service goes to standard out. When running the service in the background with `nohup`, standard output is directed to a `nohup.out` file by default (or can be redirected). Any generated output (debug messages, stack traces, etc) has no timestamp, so it's hard to reference when an event occurred.

**Comment by jtormey** [comment]
Good idea, I'm also removing a lot of the "noise" generated by the service (the "Server Time offset" logs, for example, which don't really apply to production use).

**Comment by nebaughman** [comment]
That's great - thanks @jtormey - also excellent to see Milestones! (This comment has no technical substance, just wanted to say thanks.)

**Comment by jtormey** [comment]
Logging timestamps added in PR #70, will be included in the v0.19 release.
