### ISSUE TITLE
Two factor authentication currently not enabled in the Merchant API

### ISSUE THREAD

**Issue by robsonhortela** [blockchain/service-my-wallet-v3#79]
*Service v0.19.0, Node v0.12.5*

Hi, I have a account with two factor authentication, and before update to v.19, I had normal access to this account.

Now when I try access this account I get this error:
"Two factor authentication currently not enabled in the Merchant API"
"ERR_2FA" (In the console)

There are someway to access this account?

**Comment by jtormey** [comment]
Right now, 2FA wallets can't be accessed through this service, although that is a planned feature.
