### ISSUE TITLE
All requests for API keys are ignored

### ISSUE THREAD

**Issue by vizzah** [blockchain/service-my-wallet-v3#81]
I've applied twice to get API keys and never received any reply after weeks.
What this service is for, if admins ignore API requests?
I am a blockchain.info user and want to automate payments to my contacts. When filling API request, I am asked for a 'website' and 'description of service', where I enter localhost and 'private'. There is nothing else to write? It's for internal use, not an Internet facing service. But my application is always going to the void.

**Comment by mpfluger** [comment]
To request an API code, please use this form:

https://blockchain.info/api/api_create_code

Please provide a more detailed description when submitting (like the above). If you request does not get approved, please contact our support team:

https://blockchain.zendesk.com

**Comment by vizzah** [comment]
I just tried it again and here is the response I got. This is a terrible nonsense to restrict API use to websites which Blockchain can "review".

<blockquote>We can only approve API key requests for sites we can review. If there was no site for us to review then this is why your request was denied.</blockquote>

**Comment by ibo0** [comment]
blockchain.info so bad in api service
let's use coinbase.com you can using full access api key include multi-signature bitcoin addresses

**Comment by jtormey** [comment]
Basic usage of this service doesn't require an api key. You only need an api key if you need special permissions, in which case we need to know what you're using the api for.

**Comment by vizzah** [comment]
Sending bitcoins is a basic usage. And it doesn't need a "website" or explanation from the developer. Blockchain has never granted me a key after several requests. Happy user of Blocktrail API now.

**Comment by jtormey** [comment]
The API key restriction was remove recently. Just to clarify, a key is only needed for higher request limits, larger wallet size (above several thousand addresses), and the ability to create wallets. Normal wallet functions (fetching balance, sending, receiving, address management, etc) are available form the start.

**Comment by vizzah** [comment]
Good to know you have realised that providing locked-down service is a no go. But I am not going back to using blockchain.info after experiencing complete ignorance/indifference from it's developers and admins.

**Comment by GithubUN89** [comment]
Hello,

Please answer the email's please.
I'm waiting for a response from blockchain for 2 weeks.

Regards,

**Comment by kiranGaikwad123456** [comment]
Code=ENOTFOUND
 and json response is {"error":"Request to fetch wallet timed out, check that your API key is correct"}
but my api code is valid

**Comment by vinothradhakrishnan** [comment]
hi am new one blockchain.info kindly guide me how to  call my appilcation (php) blockchain.info api and get bitcoin address and received & send  payment.

**Comment by greatmemar** [comment]
Hello,

I am trying to fill up the API request in https://blockchain.info/api/create_wallet but it only give error Captcha Code Incorrect, even I tried 100 times but same error

**Comment by PabloDeo** [comment]
If one doesn't have a website, how could one sign up for an API key? I need to write my bachelor thesis with the data from blockchain.info and I would like to bypass the request limit, for which API key is essential (if my understanding is correct).

**Comment by lfbasantos** [comment]
This is an awful service, this blockchain website. They just deny your request for the API, and there is not any clarification on why, and what to do.

**Comment by kenkit** [comment]
errr, blockchain is blocked

**Comment by adeojoemmanuel** [comment]
i keep getting " Error Request already present.  " anytime i request for any apikey without getting any response on my mail, i have made the request over and over for close to 4 months now

**Comment by akiong** [comment]
![image](https://user-images.githubusercontent.com/6744657/31701901-a07b3244-b3fd-11e7-86e2-07989717642d.png)

yes, like this one, i still don't know why i got rejected.

what i tried : 
1.  Send Request API via https://api.blockchain.info/customer/signup , i got rejected via Email
2. Ask from https://support.blockchain.com/hc/en-us/requests/new  --> not respond until now 
3. Ask from Twitter. --> not respond until now 
4. Ask from Facebook. --> not respond until now 

Can someone tell me what must i do?

**Comment by kenkit** [comment]
This you will never get

**Comment by saurabhkkr** [comment]
@jtormey please help - https://support.blockchain.com/hc/en-us/requests/338248

**Comment by proBeejay141** [comment]
Please help, have been sending request for blockchain api key since, they haven't respond in any way. Thank

**Comment by nikjlay** [comment]
ТАКАЯ ЖЕ ПРОБЛЕМА С ИМПОРТИРОВАННЫМ АДРЕСОМ 0,5БИТКОИНА ЛЕЖИТ А СНЯТЬ НЕМОГУ ТРЕБУЕТ КЛЮЧЬ

**Comment by gauravair1** [comment]
Have requested API key a few times in the last 2 weeks for our website https://bitbns.com/ This is going to be a trading platform for bitcoins in India. Haven't received any response from the blockchain team.

**Comment by kjdion84** [comment]
Ended up going with coinbase due to lack of response for an API key. Also, my website isn't even launched yet because I need to utilize an API service in order to complete the core functionality of the site.

**Comment by taroballs** [comment]
Ended up going with coinbase due to lack of response for an API key.

**Comment by kasatelli** [comment]
Tried also.. it even produces an error now

**Comment by mengmengw1** [comment]
So, if I don't have a website, how can I get an API key? Since I need some date for researches.

**Comment by RScottLewis** [comment]
I want to share with you my opinion of why there exists a  disconnect between internal blockchain developers and the rest of the programming community. There are no procedures for how to apply your API key so with the debugger I learned that your API key is taken from your certificate file and not the environment variable in Wallet.m line 118. We want to use your wallet initially within our IOS and then move to our own. Please change this (see error below) or provide a work-around. Other wallets don't have this restriction. 

How is this going to work if the Blockchain key / uuid doesn't work:
1770d5d9-bcea-4d28-ad21-6cbd5be018a8? This is your certificate not mine which I set correctly.

Failed to validate server certificate
A connection cannot be established because the server certificate could not be validated. Please check your network settings and ensure that you are using a secure connection.

HTTP load failed (error code: -999 [1:89])

**Comment by codervine** [comment]
> Basic usage of this service doesn't require an api key. You only need an api key if you need special permissions, in which case we need to know what you're using the api for.

I am currently trying to check my balance without an api key and its returning [this page](https://www.blockchain.com/api/blockchain_wallet_api). What am I not doing rightly?
