### ISSUE TITLE
error: Missing coins to spend

### ISSUE THREAD

**Issue by robsonhortela** [blockchain/service-my-wallet-v3#82]
*Service v0.19.0, Node v0.12.5*

When I try make a transfer and the account has no enough sufficent funds, the API response is:

"error":"Unexpected error, please try again".

By the way, in the log console is printed "error: Missing coins to spend"

I think the console print response should be returned in API response, cause the API response is generic and I can't show the apropriate response to the user.

**Comment by jtormey** [comment]
Good point, I'll work on making that error message less generic.

**Comment by jtormey** [comment]
Error messages for payments are more detailed in v0.20
