### ISSUE TITLE
error: There is an output too small to publish a note

### ISSUE THREAD

**Issue by robsonhortela** [blockchain/service-my-wallet-v3#83]
*Service v0.19.0, Node v0.12.5*
I'm trying make a transfer, and this message was  printed in my console. What it means?

**Comment by jtormey** [comment]
To prevent the public note feature from being spammed, we require a minimum of 500000 satoshi (0.005 btc) on every transaction output (including the change output). So you'll get this error when you're spending a small amount while trying to include a public note.
