### ISSUE TITLE
The owner of this website (blockchain.info) has banned your IP address

### ISSUE THREAD

**Issue by bitcoinservice** [blockchain/service-my-wallet-v3#86]
After one week of normal usage, the blockchain-wallet-service will not accept requests anymore, logging an HTML document that includes the following message:

`The owner of this website (blockchain.info) has banned your IP address (xxx.xxx.xxx.xxx)`

This happened more than three times already in the previous months.

I have got an API code set.

What's the cause of the problem?
What can I do so this does not happen again?

I'm also fetching addresses balance by querying `https://blockchain.info/q/getreceivedbyaddress/` which does not include an API code since the fetch address balance by confirmations in the blockchain-wallet-service was deprecated. I need to check for 0 and N confirmations also, so I had to use the blockchain.info/q/getreceivedbyaddress API.

I'm waiting for a response.
I would provide the website URL and IP, but I will do this in private messaging.

Thanks

**Comment by jtormey** [comment]
You can include your API code by adding it as a query parameter: `https://blockchain.info/q/getreceivedbyaddress/$address?api_code=$code`

If you're still having issues after that, please reach out to [our support team](https://blockchain.zendesk.com/hc/en-us). They can unban your IP and make sure your API key has the proper permissions (increased request limit).

**Comment by bitcoinservice** [comment]
@jtormey Thanks. It was not set when querying the plain-text API. This may be the source of the issue. I have just asked if the API key has the proper permissions.
