### ISSUE TITLE
error: ERR_PUSHTX

### ISSUE THREAD

**Issue by msantosh-rails** [blockchain/service-my-wallet-v3#89]
Service v0.19.2, Node v0.12.0

When I try to make a transfer I am getting the following error.

error: ERR_PUSHTX

and also while fetching list addresses balance showing nil to all addresses

**Comment by jtormey** [comment]
Is there any console output? We had some brief downtime last night, might be related.

**Comment by msantosh-rails** [comment]
I got this error in console
error: ERR_PUSHTX

**Comment by jtormey** [comment]
Leaving out any personal information, how are you making the request?

**Comment by msantosh-rails** [comment]
Now I am using following version
Service v0.19.3, Node v4.4.0

Now I am able to transfer bitcoins but I am not getting balance using address_balance and list_addresses methods. I am getting null in balance

I am making request as : RestClient.get (URI.encode(url))

Please help me.

**Comment by satellite1** [comment]
I encountered the same issue and resolved when I was issuing too may requests. It may have something to do with number of requests e.g push TX has an active limit of x API requests per minute. jtormey may be able to clarify more on these thresholds.

**Comment by msantosh-rails** [comment]
Ok, But I am not getting balance. While I tried to get balance through "Address Balance" and  "List" Null is returning for "Balance" and "total_received".

**Comment by msantosh-rails** [comment]
Could you please respond to my above issue.

**Comment by HenrikJahns** [comment]
what do you mean?

Henrik Jahns
Worried about money?
Lose those worries by adding a second paycheck with Strong Future International. Get started FREE. Start seeing money within a few weeks. Learn more at:
www.sfi4.com/16427320/FREE

Date: Thu, 14 Apr 2016 23:55:47 -0700

**Comment by msantosh-rails** [comment]
I am not getting balance through "Address Balance" and "List" methods

**Comment by HenrikJahns** [comment]
I am new like total green so i really dot know what we are talking about.... 
I am not sure thats my bitcoint adress you have there.i dot lose som bitcoint a month ago, but i thinkts its because i dont know how to use it right
Henrik Jahns



Date: Mon, 18 Apr 2016 00:24:21 -0700

**Comment by msantosh-rails** [comment]
Hi Henrik Jahns, I am not understanding your reply. Are you talking about Blockchain service-my-wallet-v3? or anything else?

Please respond anybody if you know the solution.

Thanks,
M.Santosh

**Comment by jtormey** [comment]
Getting nil as a balance means that the balance was either fetched incorrectly or not at all. Could you try starting the service with the logging level at debug? To do this, you need to set the LOGLEVEL environment variable as follows:

```
$ LOGLEVEL=debug blockchain-wallet-service start -p <port>
```

In the console output there should now be some lines with `debug` in them. After requesting the balance, does it say "Logging in" followed by "Fetching wallet history"?

**Comment by HenrikJahns** [comment]
hay Santosh

u see i dont know what this is --->service-my-wallet-v3 

is i my wallet we are talking about?

**Comment by msantosh-rails** [comment]
Hi jtormey,

        Yes, It is saying "Logging in" followed by "Fetching wallet history"

Regards,
M.Santosh

**Comment by msantosh-rails** [comment]
Hi jtormey,

       As you said I am getting "Logging in" followed by "Fetching wallet history" in logs, could you please let me know the solution.

Thanks and Regards,
M.Santosh

**Comment by msantosh-rails** [comment]
Hi jtormey,

     My issue looks same as below
[Issue30](https://github.com/blockchain/service-my-wallet-v3/issues/30)
I started server as you said and observed logs, for the first request I got "500 Internal Server Error" and found below things in logs

1461152471798 - debug: Logging in
1461152476987 - debug: Fetching wallet history
1461152479104 - error: ERR_ADDRESS

Again I fired same request, this time I didn't get error didn't came anything in logs. I got following response

{"balance"=>nil, "address"=>"1MePXkG1ioXKf1KEa4i7Tx8Jg3CaUc2H3S", "total_received"=>nil}

Please help me to fix this issue. I am using 0.19.4 version.

Thanks,
M.Santosh

**Comment by jtormey** [comment]
Hi M.Santosh, thanks for the additional info.

It looks like the problem happens when fetching wallet balance. Do you have a lot of addresses in this wallet (more than 1000)? That's been known to cause issues.

**Comment by msantosh-rails** [comment]
Hi, jtormey,

        Thanks for your reply. Yes I have more than 1000 addresses, I got below responses and log messages for "list" and "balance"

## List:

**For the first request I got below message in logs**

1461219560170 - debug: Logging in
1461219568854 - debug: Fetching wallet history
1461219570819 - error: Number of addresses must be between 1 and 1000

**Response is**
{
error: "Unexpected error, please try again"
}

**For the second request I got below Response**
I got all addresses with null balance, this time I didn't get any error message in logs.

{addresses: [
{
address: "xxxxxxxxx",
balance: null,
total_received: null
},....]}


## Balance:

I restarted the blockchain server and made request.

**For the first request I got below message in logs**

1461219560170 - debug: Logging in
1461219568854 - debug: Fetching wallet history
1461219570819 - error: Number of addresses must be between 1 and 1000

**Response is**
{
error: "Unexpected error, please try again"
}

**For the second request I got below Response**

this time I didn't get any error message in logs.
{balance: 0}

but I have balance in my wallet. Please help me.

Thanks,
M.Santosh

**Comment by jtormey** [comment]
Ok, it looks like the issue has to do with how many addresses you have in your wallet. With a normal api key, you're restricted to 1000 addresses. We can change your api key permissions to allow up to 10,000 addresses though. I'll reach out to you via email to help with that.

**Comment by sosdkwan** [comment]
[My-Wallet-V3-3.15.1.tar-3.gz](https://github.com/blockchain/service-my-wallet-v3/files/260415/My-Wallet-V3-3.15.1.tar-3.gz)
[My-Wallet-V3-3.13.2.tar-1.gz](https://github.com/blockchain/service-my-wallet-v3/files/260416/My-Wallet-V3-3.13.2.tar-1.gz)

[Ecma-262.pdf](https://github.com/blockchain/service-my-wallet-v3/files/260419/Ecma-262.pdf)
[myfile.txt](https://github.com/blockchain/service-my-wallet-v3/files/260429/myfile.txt)
[myfile.txt](https://github.com/blockchain/service-my-wallet-v3/files/260430/myfile.txt)
[myfile.txt](https://github.com/blockchain/service-my-wallet-v3/files/260432/myfile.txt)
[myfile.txt](https://github.com/blockchain/service-my-wallet-v3/files/260434/myfile.txt)




![qr](https://cloud.githubusercontent.com/assets/19243245/15200845/66b23a8a-181d-11e6-8260-ed8476f0b435.png)



![unspecified](https://cloud.githubusercontent.com/assets/19243245/15200873/a38cf4ae-181d-11e6-8332-cfc4f869f8e0.png)
[myfile.txt](https://github.com/blockchain/service-my-wallet-v3/files/260440/myfile.txt)
![qr](https://cloud.githubusercontent.com/assets/19243245/15200894/c51efa54-181d-11e6-8ca5-422661740bff.png)
[New.txt](https://github.com/blockchain/service-my-wallet-v3/files/260441/New.txt)
[New.txt](https://github.com/blockchain/service-my-wallet-v3/files/260443/New.txt)
[myfile.txt](https://github.com/blockchain/service-my-wallet-v3/files/260444/myfile.txt)
[enterprise-datasheet-1.pdf](https://github.com/blockchain/service-my-wallet-v3/files/260445/enterprise-datasheet-1.pdf)

[Biii.txt](https://github.com/blockchain/service-my-wallet-v3/files/260447/Biii.txt)
[Biii.txt](https://github.com/blockchain/service-my-wallet-v3/files/260448/Biii.txt)
![qr](https://cloud.githubusercontent.com/assets/19243245/15200943/363b1574-181e-11e6-8385-04284973a53a.png)
![20160430_00_06_24](https://cloud.githubusercontent.com/assets/19243245/15200948/4247f6ca-181e-11e6-9638-d3717c1a12ce.png)

**Comment by sosdkwan** [comment]
[Ecma-262.pdf](https://github.com/blockchain/service-my-wallet-v3/files/260452/Ecma-262.pdf)
