### ISSUE TITLE
archiving an HD account returns success but nothing happens

### ISSUE THREAD

**Issue by radiumsoup** [blockchain/service-my-wallet-v3#93]
Using service 0.19.3, node 0.12.0

I am having trouble implementing the '/merchant/:guid/accounts/:xpub_or_index/archive' endpoint using an xpub id - I get a proper response as expected with the object details for the account, and it has a '1' in the field 'archived', where normally it is just null - so I am getting a response that indicates success. But when I list the active accounts again using the endpoint '/merchant/:guid/accounts', that account (which shouldn't be listed at all) shows up again with a null in the 'archived' field - but even if it is listed, it should have the archive flag set. 

Same behavior, by the way, when using the index instead of the xpub.

**Comment by jtormey** [comment]
Hey, thanks for pointing this issue out. It's been fixed in the latest patch (v0.19.4). Upgrade and then everything should run smoothly!
