### ISSUE TITLE
unexpected ERR_AUTH

### ISSUE THREAD

**Issue by mitalcoi** [blockchain/service-my-wallet-v3#96]
*Service v0.19.3, Node v5.1.0*
I'm trying to fetch balance of my wallet but getting an error:

```1460713952470 - error: ERR_AUTH
{"initial_error":"Authorization Required. Please check your email.", "extra_seed":"bfc167f428289852bf6a010380a5da3d22642b1f2c629b7bf14f29bbf1a05b56944687dda31d84bc191361d57a34ceb3eef9c0aab6c4aaa76d3f2a40b8be0b86","symbol_local":{"symbol":"$","code":"USD","symbolAppearsAfter":false,"name":"U.S. dollar","local":true,"conversion":234747.29453743},"clientTimeDiff":235,"serverTime":1460714003981,"war_checksum":"7f9938b315aecbf0","language":"en","authorization_required":true,"symbol_btc":{"symbol":"BTC","code":"BTC","symbolAppearsAfter":true,"name":"Bitcoin","local":false,"conversion":100000000.00000000}```
Then I got an email with confirmation link. I followed the link, trying to call api method once again, but the error remains

**Comment by jtormey** [comment]
Hey, sorry, at the moment email protected wallets aren't API accessible.

**Comment by tadejgasparovic** [comment]
Hey! I was having the same problem and this is how I solved it.

1. Login to your Blockchain wallet
2. Go to Settings->Security
3. Click on "Advanced Settings"
4. Add the IP you're using to access the wallet to the IP Whitelist

Hope this helped you! :)

**Comment by Lalitpatadiya12** [comment]
@tadejgasparovic : Is their any way to do using API because I have faced the same problem.

**Comment by tadejgasparovic** [comment]
No, unfortunately not.

14. mar. 2017 06.09 je oseba "Lalitpatadiya12" <notifications@github.com>
napisala:
